# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0002_initial'),
        ('kas_bank', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kasbanktransaction',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_mutasi', to='produk.gudang', verbose_name='Cabang/Gudang'),
        ),
        migrations.AddField(
            model_name='kasbanktransaction',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kasbanktransaction',
            name='jurnal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_mutasi', to='akuntansi.jurnalentry', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='kasbanktransaction',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_mutasi', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddField(
            model_name='kasbanktransfer',
            name='akun_biaya_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_transfer_biaya_admin', to='akuntansi.akun', verbose_name='Akun Biaya Admin'),
        ),
        migrations.AddField(
            model_name='kasbanktransfer',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_transfer', to='produk.gudang', verbose_name='Cabang/Gudang'),
        ),
        migrations.AddField(
            model_name='kasbanktransfer',
            name='dari_akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_keluar', to='kas_bank.kasbankaccount', verbose_name='Dari Akun'),
        ),
        migrations.AddField(
            model_name='kasbanktransfer',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_transfers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kasbanktransfer',
            name='jurnal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kas_bank_transfer', to='akuntansi.jurnalentry', verbose_name='Jurnal'),
        ),
        migrations.AddField(
            model_name='kasbanktransfer',
            name='ke_akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_masuk', to='kas_bank.kasbankaccount', verbose_name='Ke Akun'),
        ),
        migrations.AddIndex(
            model_name='kasbankaccount',
            index=models.Index(fields=['tipe', 'aktif'], name='kb_acc_tipe_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbankaccount',
            index=models.Index(fields=['aktif', 'is_default'], name='kb_acc_default_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbankreconciliation',
            index=models.Index(fields=['akun_kas_bank', 'status', 'tanggal_akhir'], name='kb_rek_akun_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbankreconciliation',
            index=models.Index(fields=['status', 'tanggal_akhir'], name='kb_rek_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['sumber_app', 'sumber_model', 'sumber_id'], name='kas_bank_ka_sumber__5b5482_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['tanggal', 'status'], name='kas_bank_ka_tanggal_ad7343_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['akun_kas_bank', 'status', 'tanggal'], name='kb_mut_akun_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['cabang', 'tanggal'], name='kb_mut_cabang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['metode_pembayaran', 'status', 'tanggal'], name='kb_mut_metode_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['status', 'tanggal'], name='kb_trf_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['dari_akun', 'status'], name='kb_trf_dari_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['ke_akun', 'status'], name='kb_trf_ke_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['cabang', 'tanggal'], name='kb_trf_cabang_tgl_idx'),
        ),
    ]
