# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
        ('kas_bank', '0001_initial'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kasbankaccount',
            index=models.Index(fields=['tipe', 'aktif'], name='kb_acc_tipe_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbankaccount',
            index=models.Index(fields=['aktif', 'is_default'], name='kb_acc_default_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbankreconciliation',
            index=models.Index(fields=['akun_kas_bank', 'status', 'tanggal_akhir'], name='kb_rek_akun_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbankreconciliation',
            index=models.Index(fields=['status', 'tanggal_akhir'], name='kb_rek_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['akun_kas_bank', 'status', 'tanggal'], name='kb_mut_akun_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['cabang', 'tanggal'], name='kb_mut_cabang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransaction',
            index=models.Index(fields=['metode_pembayaran', 'status', 'tanggal'], name='kb_mut_metode_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['status', 'tanggal'], name='kb_trf_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['dari_akun', 'status'], name='kb_trf_dari_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['ke_akun', 'status'], name='kb_trf_ke_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kasbanktransfer',
            index=models.Index(fields=['cabang', 'tanggal'], name='kb_trf_cabang_tgl_idx'),
        ),
    ]
