# Generated by Django 6.0.3 on 2026-06-06 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0005_add_is_reversed_to_jurnalentry'),
        ('kas_bank', '0002_performance_indexes'),
        ('pos', '0012_alter_metodepembayaran_gambar'),
        ('produk', '0010_produk_tipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kasbanktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted')), fields=('sumber_app', 'sumber_model', 'sumber_id', 'tipe', 'akun_kas_bank'), name='unique_posted_kas_bank_mutation'),
        ),
    ]
