# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Satuan')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('jumlah_konversi', models.DecimalField(decimal_places=4, default=0, help_text='Jumlah dalam satuan dasar produk, dihitung otomatis', max_digits=15, verbose_name='Jumlah (Satuan Dasar)')),
                ('catatan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Item PO',
                'verbose_name_plural': 'Item PO',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Supplier')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Supplier')),
                ('kontak', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kontak Person')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplier',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_po', models.CharField(max_length=50, unique=True, verbose_name='Nomor PO')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('received', 'Diterima'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pajak')),
                ('biaya_pengiriman', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya Pengiriman/Ongkir')),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Harga')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_dibuat', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_disetujui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
