# Generated by Django 5.0.6 on 2026-01-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='tanggal',
            field=models.DateTimeField(verbose_name='Tanggal'),
        ),
    ]
