# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pembelian', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='produk.gudang', verbose_name='Gudang Tujuan'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk', verbose_name='Produk'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pembelian.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='satuan_transaksi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika menggunakan satuan asli produk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.satuan', verbose_name='Satuan Transaksi'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['aktif', 'nama'], name='purch_sup_aktif_idx'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='pembelian.supplier', verbose_name='Supplier'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['produk', 'purchase_order'], name='purch_item_prod_po_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tanggal', 'status'], name='purch_po_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purch_po_sup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['gudang', 'tanggal'], name='purch_po_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='purch_po_pay_status_idx'),
        ),
    ]
