# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0004_purchaseorderitem_jumlah_konversi_and_more'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tanggal', 'status'], name='purch_po_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purch_po_sup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['gudang', 'tanggal'], name='purch_po_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='purch_po_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['produk', 'purchase_order'], name='purch_item_prod_po_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['aktif', 'nama'], name='purch_sup_aktif_idx'),
        ),
    ]
