# Generated by Django 5.0.6 on 2026-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=200, verbose_name='Nama Perusahaan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perusahaan/', verbose_name='Logo')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('pajak_default', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pajak Default (%)')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Perusahaan',
                'verbose_name_plural': 'Pengaturan Perusahaan',
            },
        ),
    ]
