# Generated by Django 5.0.6 on 2026-06-02 01:08

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=200, verbose_name='Nama Perusahaan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='perusahaan/', validators=[apps.core.validators.validate_image_file], verbose_name='Logo')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('system_title', models.CharField(default='SERPTECH', max_length=200, verbose_name='Judul Sistem')),
                ('system_description', models.TextField(blank=True, help_text='Deskripsi singkat tentang sistem (untuk meta description)', null=True, verbose_name='Deskripsi Sistem')),
                ('system_keywords', models.CharField(blank=True, help_text='Pisahkan dengan koma. Contoh: erp, inventory, pos', max_length=500, null=True, verbose_name='Keywords (SEO)')),
                ('system_logo', models.ImageField(blank=True, help_text='Logo yang ditampilkan di sidebar & login page', null=True, upload_to='system/', validators=[apps.core.validators.validate_image_file], verbose_name='Logo Sistem')),
                ('system_favicon', models.ImageField(blank=True, help_text='Icon yang tampil di tab browser (.ico atau .png 32x32)', null=True, upload_to='system/', validators=[apps.core.validators.validate_image_file], verbose_name='Favicon')),
                ('auth_image', models.ImageField(blank=True, help_text='Gambar utama pada halaman Login/Register (rekomendasi: PNG transparan)', null=True, upload_to='system/auth/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar Ilustrasi Autentikasi (Kiri)')),
                ('auth_background_image', models.ImageField(blank=True, help_text='Gambar shape abstract atau background (rekomendasi: SVG atau PNG transparan)', null=True, upload_to='system/auth/', validators=[apps.core.validators.validate_image_file], verbose_name='Background Mask Autentikasi')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Aktifkan untuk menampilkan halaman maintenance', verbose_name='Mode Maintenance')),
                ('maintenance_message', models.TextField(blank=True, default='Sistem sedang dalam maintenance. Silakan coba lagi nanti.', verbose_name='Pesan Maintenance')),
                ('misc_image', models.ImageField(blank=True, help_text='Gambar utama pada halaman Error & Maintenance (rekomendasi: PNG transparan)', null=True, upload_to='system/misc/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar Ilustrasi Halaman Error & Maintenance')),
                ('misc_background_image', models.ImageField(blank=True, help_text='Gambar latar belakang untuk halaman rupa-rupa (rekomendasi: SVG atau PNG transparan)', null=True, upload_to='system/misc/', validators=[apps.core.validators.validate_image_file], verbose_name='Background Halaman Error & Maintenance')),
                ('email_smtp_host', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='SMTP Host')),
                ('email_smtp_port', models.IntegerField(default=587, verbose_name='SMTP Port')),
                ('email_smtp_user', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email SMTP User')),
                ('email_smtp_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email SMTP Password')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('email_header', models.TextField(default='Halo,', help_text='Header yang muncul di awal email', verbose_name='Email Header')),
                ('email_footer', models.TextField(default='Terima kasih,\n{company_name}', help_text='Footer yang muncul di akhir email. Gunakan {company_name} untuk nama perusahaan', verbose_name='Email Footer')),
                ('forgot_password_subject', models.CharField(default='Reset Password Anda', max_length=200, verbose_name='Subjek Email Forgot Password')),
                ('forgot_password_message', models.TextField(default='Anda menerima email ini karena ada permintaan reset password untuk akun Anda.\n\nKlik link berikut untuk reset password:\n{reset_link}\n\nJika Anda tidak melakukan permintaan ini, abaikan email ini.', help_text='Gunakan {reset_link} untuk link reset password', verbose_name='Pesan Forgot Password')),
                ('register_subject', models.CharField(default='Verifikasi Email Anda', max_length=200, verbose_name='Subjek Email Register')),
                ('register_message', models.TextField(default='Terima kasih telah mendaftar di sistem kami.\n\nSilakan verifikasi email Anda dengan klik link berikut:\n{verification_link}\n\nLink ini akan kadaluarsa dalam 24 jam.', help_text='Gunakan {verification_link} untuk link verifikasi', verbose_name='Pesan Register')),
                ('pajak_default', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pajak Default (%)')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Perusahaan',
                'verbose_name_plural': 'Pengaturan Perusahaan',
            },
        ),
        migrations.CreateModel(
            name='TemplateCetak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('jenis', models.CharField(choices=[('invoice', 'Invoice'), ('pos_invoice', 'Invoice POS'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('expense', 'Transaksi Biaya'), ('slip_gaji', 'Slip Gaji'), ('export_excel', 'Export Excel'), ('export_pdf', 'Export PDF')], max_length=20, unique=True, verbose_name='Jenis Dokumen')),
                ('header_nama_perusahaan', models.CharField(default='SERPTECH', max_length=200, verbose_name='Nama Perusahaan')),
                ('header_alamat', models.TextField(default='Jl. Contoh Alamat No. 123, Jakarta 12345', verbose_name='Alamat')),
                ('header_telepon', models.CharField(default='(021) 1234-5678', max_length=50, verbose_name='Telepon')),
                ('header_email', models.EmailField(default='info@starterkit.com', max_length=254, verbose_name='Email')),
                ('header_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('footer_ucapan', models.CharField(default='Terima kasih atas kepercayaan Anda!', max_length=200, verbose_name='Ucapan Terima Kasih')),
                ('footer_keterangan', models.CharField(default='Dokumen ini dicetak secara otomatis dan sah tanpa tanda tangan.', max_length=200, verbose_name='Keterangan')),
                ('footer_copyright', models.CharField(default='© 2026 SERPTECH', max_length=200, verbose_name='Footer Copyright')),
                ('signature_kiri_label', models.CharField(default='Disetujui Oleh', max_length=50, verbose_name='Label Tanda Tangan Kiri')),
                ('signature_kanan_label', models.CharField(default='Dibuat Oleh', max_length=50, verbose_name='Label Tanda Tangan Kanan')),
                ('tampilkan_logo', models.BooleanField(default=True, verbose_name='Tampilkan Logo')),
                ('tampilkan_website', models.BooleanField(default=False, verbose_name='Tampilkan Website')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Cetak',
                'verbose_name_plural': 'Template Cetak',
                'ordering': ['jenis'],
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255, verbose_name='Nama File')),
                ('ukuran_file', models.BigIntegerField(default=0, verbose_name='Ukuran File (bytes)')),
                ('jenis', models.CharField(choices=[('backup', 'Backup Data'), ('restore', 'Restore Data'), ('reset', 'Reset Data')], max_length=10, verbose_name='Jenis Aktivitas')),
                ('status', models.CharField(choices=[('sukses', 'Sukses'), ('gagal', 'Gagal')], default='sukses', max_length=10, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_histories', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Riwayat Backup',
                'verbose_name_plural': 'Riwayat Backup',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
