# Generated by Django 5.0.6 on 2026-01-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCetak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('jenis', models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order')], max_length=20, unique=True, verbose_name='Jenis Dokumen')),
                ('header_nama_perusahaan', models.CharField(default='PT. STARTER KIT ERP', max_length=200, verbose_name='Nama Perusahaan')),
                ('header_alamat', models.TextField(default='Jl. Contoh Alamat No. 123, Jakarta 12345', verbose_name='Alamat')),
                ('header_telepon', models.CharField(default='(021) 1234-5678', max_length=50, verbose_name='Telepon')),
                ('header_email', models.EmailField(default='info@starterkit.com', max_length=254, verbose_name='Email')),
                ('header_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('footer_ucapan', models.CharField(default='Terima kasih atas kepercayaan Anda!', max_length=200, verbose_name='Ucapan Terima Kasih')),
                ('footer_keterangan', models.CharField(default='Dokumen ini dicetak secara otomatis dan sah tanpa tanda tangan.', max_length=200, verbose_name='Keterangan')),
                ('signature_kiri_label', models.CharField(default='Disetujui Oleh', max_length=50, verbose_name='Label Tanda Tangan Kiri')),
                ('signature_kanan_label', models.CharField(default='Dibuat Oleh', max_length=50, verbose_name='Label Tanda Tangan Kanan')),
                ('tampilkan_logo', models.BooleanField(default=True, verbose_name='Tampilkan Logo')),
                ('tampilkan_website', models.BooleanField(default=False, verbose_name='Tampilkan Website')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Cetak',
                'verbose_name_plural': 'Template Cetak',
                'ordering': ['jenis'],
            },
        ),
    ]
