# Generated by Django 5.0.6 on 2026-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0002_templatecetak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('expense', 'Transaksi Biaya')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
