# Generated by Django 5.0.6 on 2026-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0003_alter_templatecetak_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email SMTP Password'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_smtp_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email SMTP User'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
    ]
