# Generated by Django 5.0.6 on 2026-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0004_pengaturanperusahaan_email_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_footer',
            field=models.TextField(default='Terima kasih,\n{company_name}', help_text='Footer yang muncul di akhir email. Gunakan {company_name} untuk nama perusahaan', verbose_name='Email Footer'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='email_header',
            field=models.TextField(default='Halo,', help_text='Header yang muncul di awal email', verbose_name='Email Header'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='forgot_password_message',
            field=models.TextField(default='Anda menerima email ini karena ada permintaan reset password untuk akun Anda.\n\nKlik link berikut untuk reset password:\n{reset_link}\n\nJika Anda tidak melakukan permintaan ini, abaikan email ini.', help_text='Gunakan {reset_link} untuk link reset password', verbose_name='Pesan Forgot Password'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='forgot_password_subject',
            field=models.CharField(default='Reset Password Anda', max_length=200, verbose_name='Subjek Email Forgot Password'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='register_message',
            field=models.TextField(default='Terima kasih telah mendaftar di sistem kami.\n\nSilakan verifikasi email Anda dengan klik link berikut:\n{verification_link}\n\nLink ini akan kadaluarsa dalam 24 jam.', help_text='Gunakan {verification_link} untuk link verifikasi', verbose_name='Pesan Register'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='register_subject',
            field=models.CharField(default='Verifikasi Email Anda', max_length=200, verbose_name='Subjek Email Register'),
        ),
    ]
