# Generated by Django 5.0.6 on 2026-02-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0005_pengaturanperusahaan_email_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='deskripsi_sistem',
            field=models.TextField(blank=True, help_text='Deskripsi singkat sistem untuk SEO dan footer login', null=True, verbose_name='Deskripsi Sistem (Meta)'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='perusahaan/', verbose_name='Favicon System'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='meta_author',
            field=models.CharField(blank=True, default='Admin', max_length=100, null=True, verbose_name='Meta Author'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kata kunci untuk SEO, pisahkan dengan koma', max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
    ]
