# Generated by Django 5.0.6 on 2026-02-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0006_pengaturanperusahaan_deskripsi_sistem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='deskripsi_sistem',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='meta_author',
        ),
        migrations.RemoveField(
            model_name='pengaturanperusahaan',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='maintenance_message',
            field=models.TextField(blank=True, default='Sistem sedang dalam maintenance. Silakan coba lagi nanti.', verbose_name='Pesan Maintenance'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk menampilkan halaman maintenance', verbose_name='Mode Maintenance'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_description',
            field=models.TextField(blank=True, help_text='Deskripsi singkat tentang sistem (untuk meta description)', null=True, verbose_name='Deskripsi Sistem'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_favicon',
            field=models.ImageField(blank=True, help_text='Icon yang tampil di tab browser (.ico atau .png 32x32)', null=True, upload_to='system/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_keywords',
            field=models.CharField(blank=True, help_text='Pisahkan dengan koma. Contoh: erp, inventory, pos', max_length=500, null=True, verbose_name='Keywords (SEO)'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_logo',
            field=models.ImageField(blank=True, help_text='Logo yang ditampilkan di sidebar & login page', null=True, upload_to='system/', verbose_name='Logo Sistem'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='system_title',
            field=models.CharField(default='ERP System', max_length=200, verbose_name='Judul Sistem'),
        ),
    ]
