# Generated by Django 5.0.6 on 2026-02-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0007_remove_pengaturanperusahaan_deskripsi_sistem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatecetak',
            name='footer_copyright',
            field=models.CharField(default='© 2026 PT. Starter Kit ERP', max_length=200, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('expense', 'Transaksi Biaya'), ('export_excel', 'Export Excel'), ('export_pdf', 'Export PDF')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
