# Generated by Django 5.0.6 on 2026-02-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0008_add_export_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(max_length=255, verbose_name='Nama File')),
                ('ukuran_file', models.BigIntegerField(default=0, verbose_name='Ukuran File (bytes)')),
                ('jenis', models.CharField(choices=[('backup', 'Backup Data'), ('restore', 'Restore Data'), ('reset', 'Reset Data')], max_length=10, verbose_name='Jenis Aktivitas')),
                ('status', models.CharField(choices=[('sukses', 'Sukses'), ('gagal', 'Gagal')], default='sukses', max_length=10, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_histories', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Riwayat Backup',
                'verbose_name_plural': 'Riwayat Backup',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
