# Generated by Django 5.0.6 on 2026-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0009_backuphistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('expense', 'Transaksi Biaya'), ('slip_gaji', 'Slip Gaji'), ('export_excel', 'Export Excel'), ('export_pdf', 'Export PDF')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
