# Generated by Django 5.0.6 on 2026-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0010_add_slip_gaji_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='auth_background_image',
            field=models.ImageField(blank=True, help_text='Gambar shape abstract atau background (rekomendasi: SVG atau PNG transparan)', null=True, upload_to='system/auth/', verbose_name='Background Mask Autentikasi'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='auth_image',
            field=models.ImageField(blank=True, help_text='Gambar utama pada halaman Login/Register (rekomendasi: PNG transparan)', null=True, upload_to='system/auth/', verbose_name='Gambar Ilustrasi Autentikasi (Kiri)'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='system_title',
            field=models.CharField(default='SERPTECH', max_length=200, verbose_name='Judul Sistem'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='footer_copyright',
            field=models.CharField(default='© 2026 SERPTECH', max_length=200, verbose_name='Footer Copyright'),
        ),
        migrations.AlterField(
            model_name='templatecetak',
            name='header_nama_perusahaan',
            field=models.CharField(default='SERPTECH', max_length=200, verbose_name='Nama Perusahaan'),
        ),
    ]
