# Generated by Django 6.0.3 on 2026-04-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0011_pengaturanperusahaan_auth_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='misc_background_image',
            field=models.ImageField(blank=True, help_text='Gambar latar belakang untuk halaman rupa-rupa (rekomendasi: SVG atau PNG transparan)', null=True, upload_to='system/misc/', verbose_name='Background Halaman Error & Maintenance'),
        ),
        migrations.AddField(
            model_name='pengaturanperusahaan',
            name='misc_image',
            field=models.ImageField(blank=True, help_text='Gambar utama pada halaman Error & Maintenance (rekomendasi: PNG transparan)', null=True, upload_to='system/misc/', verbose_name='Gambar Ilustrasi Halaman Error & Maintenance'),
        ),
    ]
