# Generated by Django 6.0.3 on 2026-05-22 09:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0012_pengaturanperusahaan_misc_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='auth_background_image',
            field=models.ImageField(blank=True, help_text='Gambar shape abstract atau background (rekomendasi: SVG atau PNG transparan)', null=True, upload_to='system/auth/', validators=[apps.core.validators.validate_image_file], verbose_name='Background Mask Autentikasi'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='auth_image',
            field=models.ImageField(blank=True, help_text='Gambar utama pada halaman Login/Register (rekomendasi: PNG transparan)', null=True, upload_to='system/auth/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar Ilustrasi Autentikasi (Kiri)'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='perusahaan/', validators=[apps.core.validators.validate_image_file], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='misc_background_image',
            field=models.ImageField(blank=True, help_text='Gambar latar belakang untuk halaman rupa-rupa (rekomendasi: SVG atau PNG transparan)', null=True, upload_to='system/misc/', validators=[apps.core.validators.validate_image_file], verbose_name='Background Halaman Error & Maintenance'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='misc_image',
            field=models.ImageField(blank=True, help_text='Gambar utama pada halaman Error & Maintenance (rekomendasi: PNG transparan)', null=True, upload_to='system/misc/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar Ilustrasi Halaman Error & Maintenance'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='system_favicon',
            field=models.ImageField(blank=True, help_text='Icon yang tampil di tab browser (.ico atau .png 32x32)', null=True, upload_to='system/', validators=[apps.core.validators.validate_image_file], verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='pengaturanperusahaan',
            name='system_logo',
            field=models.ImageField(blank=True, help_text='Logo yang ditampilkan di sidebar & login page', null=True, upload_to='system/', validators=[apps.core.validators.validate_image_file], verbose_name='Logo Sistem'),
        ),
    ]
