# Generated by Django 6.0.3 on 2026-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0013_alter_pengaturanperusahaan_auth_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatecetak',
            name='jenis',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('pos_invoice', 'Invoice POS'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('expense', 'Transaksi Biaya'), ('slip_gaji', 'Slip Gaji'), ('export_excel', 'Export Excel'), ('export_pdf', 'Export PDF')], max_length=20, unique=True, verbose_name='Jenis Dokumen'),
        ),
    ]
