# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=50, unique=True, verbose_name='No. Piutang')),
                ('sumber', models.CharField(choices=[('so', 'Sales Order'), ('pos', 'POS (Kasbon)'), ('manual', 'Input Manual')], default='manual', max_length=10, verbose_name='Sumber')),
                ('sumber_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='No. Referensi Sumber')),
                ('jumlah_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Total')),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Dibayar')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Piutang')),
                ('jatuh_tempo', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('sebagian', 'Bayar Sebagian'), ('lunas', 'Lunas'), ('macet', 'Macet'), ('dihapuskan', 'Dihapuskan')], default='belum_bayar', max_length=15, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Piutang',
                'verbose_name_plural': 'Piutang',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranPiutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Bayar')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah Bayar')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dicatat Oleh')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.jurnalentry', verbose_name='Jurnal Entry')),
            ],
            options={
                'verbose_name': 'Pembayaran Piutang',
                'verbose_name_plural': 'Pembayaran Piutang',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
