# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0002_initial'),
        ('penjualan', '0002_initial'),
        ('piutang', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaranpiutang',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddField(
            model_name='piutang',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='piutang',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='piutang',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piutang_set', to='penjualan.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='piutang',
            name='jurnal_pembayaran',
            field=models.ForeignKey(blank=True, help_text='Jurnal otomatis saat piutang dibayar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_piutang', to='akuntansi.jurnalentry', verbose_name='Jurnal Pembayaran'),
        ),
        migrations.AddField(
            model_name='piutang',
            name='pos_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_set', to='pos.postransaction', verbose_name='POS Transaction'),
        ),
        migrations.AddField(
            model_name='piutang',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piutang_set', to='penjualan.salesorder', verbose_name='Sales Order'),
        ),
        migrations.AddField(
            model_name='pembayaranpiutang',
            name='piutang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_set', to='piutang.piutang', verbose_name='Piutang'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['tanggal', 'status'], name='ar_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['jatuh_tempo', 'status'], name='ar_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['customer', 'status'], name='ar_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['cabang', 'status'], name='ar_cabang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['sumber', 'sumber_ref'], name='ar_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranpiutang',
            index=models.Index(fields=['tanggal'], name='ar_pay_tanggal_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranpiutang',
            index=models.Index(fields=['piutang', 'tanggal'], name='ar_pay_piutang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranpiutang',
            index=models.Index(fields=['metode_pembayaran', 'tanggal'], name='ar_pay_metode_tgl_idx'),
        ),
    ]
