# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
        ('penjualan', '0005_performance_indexes'),
        ('piutang', '0002_piutang_jurnal_pembayaran'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pembayaranpiutang',
            index=models.Index(fields=['tanggal'], name='ar_pay_tanggal_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranpiutang',
            index=models.Index(fields=['piutang', 'tanggal'], name='ar_pay_piutang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranpiutang',
            index=models.Index(fields=['metode_pembayaran', 'tanggal'], name='ar_pay_metode_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['tanggal', 'status'], name='ar_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['jatuh_tempo', 'status'], name='ar_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['customer', 'status'], name='ar_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['cabang', 'status'], name='ar_cabang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='piutang',
            index=models.Index(fields=['sumber', 'sumber_ref'], name='ar_source_ref_idx'),
        ),
    ]
