# Generated by Django 6.0.3 on 2026-05-09 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0001_initial'),
        ('pembelian', '0004_purchaseorderitem_jumlah_konversi_and_more'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsetTetap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True, verbose_name='Kode Aset')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Aset')),
                ('kategori', models.CharField(choices=[('peralatan', 'Peralatan'), ('kendaraan', 'Kendaraan'), ('bangunan', 'Bangunan'), ('tanah', 'Tanah'), ('mesin', 'Mesin'), ('inventaris', 'Inventaris Kantor'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Kategori')),
                ('deskripsi', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('harga_perolehan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Perolehan')),
                ('nilai_residu', models.DecimalField(decimal_places=2, default=0, help_text='Estimasi nilai saat habis umur ekonomis', max_digits=15, verbose_name='Nilai Residu')),
                ('umur_ekonomis', models.IntegerField(help_text='Lama pemakaian dalam bulan', verbose_name='Umur Ekonomis (Bulan)')),
                ('tanggal_perolehan', models.DateField(verbose_name='Tanggal Perolehan')),
                ('metode_penyusutan', models.CharField(choices=[('garis_lurus', 'Garis Lurus (Straight-Line)'), ('saldo_menurun', 'Saldo Menurun Ganda (Double-Declining)')], default='garis_lurus', max_length=20, verbose_name='Metode Penyusutan')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('dijual', 'Dijual'), ('dihapuskan', 'Dihapuskan'), ('rusak', 'Rusak/Tidak Terpakai')], default='aktif', max_length=15, verbose_name='Status')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('akun_aset', models.ForeignKey(blank=True, help_text='Akun neraca untuk aset ini (misal: 1-4000 Peralatan)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aset_tetap_set', to='akuntansi.akun', verbose_name='Akun Aset (CoA)')),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aset_tetap_set', to='produk.gudang', verbose_name='Cabang/Lokasi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembelian.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Aset Tetap',
                'verbose_name_plural': 'Aset Tetap',
                'ordering': ['-tanggal_perolehan'],
            },
        ),
        migrations.CreateModel(
            name='DisposalAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('jual', 'Dijual'), ('hapus', 'Dihapuskan')], max_length=10, verbose_name='Tipe Disposal')),
                ('tanggal', models.DateField(verbose_name='Tanggal Disposal')),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, help_text='0 jika dihapuskan', max_digits=15, verbose_name='Harga Jual')),
                ('nilai_buku_saat_disposal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nilai Buku saat Disposal')),
                ('laba_rugi', models.DecimalField(decimal_places=2, default=0, help_text='Positif=Laba, Negatif=Rugi', max_digits=15, verbose_name='Laba/Rugi Disposal')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_set', to='aset.asettetap', verbose_name='Aset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.jurnalentry', verbose_name='Jurnal Entry')),
            ],
            options={
                'verbose_name': 'Disposal Aset',
                'verbose_name_plural': 'Disposal Aset',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Penyusutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.IntegerField(verbose_name='Bulan (1-12)')),
                ('tahun', models.IntegerField(verbose_name='Tahun')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah Penyusutan')),
                ('akumulasi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Akumulasi s/d Bulan Ini')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('aset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penyusutan_set', to='aset.asettetap', verbose_name='Aset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.jurnalentry', verbose_name='Jurnal Entry')),
            ],
            options={
                'verbose_name': 'Penyusutan',
                'verbose_name_plural': 'Penyusutan',
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('aset', 'bulan', 'tahun')},
            },
        ),
    ]
