# Generated by Django 6.0.3 on 2026-05-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0001_initial'),
        ('aset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asettetap',
            name='jurnal_penyusutan',
            field=models.ForeignKey(blank=True, help_text='Jurnal otomatis untuk penyusutan bulanan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyusutan_aset', to='akuntansi.jurnalentry', verbose_name='Jurnal Penyusutan'),
        ),
    ]
