# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0002_initial'),
        ('aset', '0001_initial'),
        ('pembelian', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asettetap',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aset_tetap_set', to='produk.gudang', verbose_name='Cabang/Lokasi'),
        ),
        migrations.AddField(
            model_name='asettetap',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='asettetap',
            name='jurnal_penyusutan',
            field=models.ForeignKey(blank=True, help_text='Jurnal otomatis untuk penyusutan bulanan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyusutan_aset', to='akuntansi.jurnalentry', verbose_name='Jurnal Penyusutan'),
        ),
        migrations.AddField(
            model_name='asettetap',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembelian.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='disposalaset',
            name='aset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_set', to='aset.asettetap', verbose_name='Aset'),
        ),
        migrations.AddField(
            model_name='disposalaset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disposalaset',
            name='jurnal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.jurnalentry', verbose_name='Jurnal Entry'),
        ),
        migrations.AddField(
            model_name='penyusutan',
            name='aset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penyusutan_set', to='aset.asettetap', verbose_name='Aset'),
        ),
        migrations.AddField(
            model_name='penyusutan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penyusutan',
            name='jurnal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.jurnalentry', verbose_name='Jurnal Entry'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['status', 'tanggal_perolehan'], name='asset_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['cabang', 'status'], name='asset_cabang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['supplier', 'status'], name='asset_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['kategori', 'status'], name='asset_kategori_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalaset',
            index=models.Index(fields=['tanggal', 'tipe'], name='asset_disp_tgl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalaset',
            index=models.Index(fields=['aset', 'tanggal'], name='asset_disp_asset_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='penyusutan',
            index=models.Index(fields=['tahun', 'bulan'], name='depr_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='penyusutan',
            index=models.Index(fields=['aset', 'tahun'], name='depr_asset_year_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='penyusutan',
            unique_together={('aset', 'bulan', 'tahun')},
        ),
    ]
