# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
        ('aset', '0002_asettetap_jurnal_penyusutan'),
        ('pembelian', '0004_purchaseorderitem_jumlah_konversi_and_more'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['status', 'tanggal_perolehan'], name='asset_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['cabang', 'status'], name='asset_cabang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['supplier', 'status'], name='asset_supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='asettetap',
            index=models.Index(fields=['kategori', 'status'], name='asset_kategori_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalaset',
            index=models.Index(fields=['tanggal', 'tipe'], name='asset_disp_tgl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalaset',
            index=models.Index(fields=['aset', 'tanggal'], name='asset_disp_asset_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='penyusutan',
            index=models.Index(fields=['tahun', 'bulan'], name='depr_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='penyusutan',
            index=models.Index(fields=['aset', 'tahun'], name='depr_asset_year_idx'),
        ),
    ]
