# Generated by Django 5.0.6 on 2026-02-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERUSER', 'Superuser - Full Access'), ('ADMIN', 'Admin - Limited Access'), ('USER', 'User - Read & Create Only'), ('KASIR', 'Kasir - POS Access Only')], max_length=20, verbose_name='Role')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan')], max_length=50, verbose_name='Module')),
                ('can_view', models.BooleanField(default=True, help_text='Dapat melihat/membaca data', verbose_name='Can View')),
                ('can_create', models.BooleanField(default=False, help_text='Dapat menambah data baru', verbose_name='Can Create')),
                ('can_edit', models.BooleanField(default=False, help_text='Dapat mengubah data', verbose_name='Can Edit')),
                ('can_delete', models.BooleanField(default=False, help_text='Dapat menghapus data', verbose_name='Can Delete')),
                ('description', models.TextField(blank=True, help_text='Catatan tambahan tentang permission ini', null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role', 'module'],
                'unique_together': {('role', 'module')},
            },
        ),
    ]
