# Generated by Django 5.0.6 on 2026-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kunci Lisensi')),
                ('hardware_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hardware ID')),
                ('cls_server_url', models.URLField(default='https://cls.serpgroup.cloud', help_text='Alamat server CLS (contoh: https://cls.serpgroup.cloud)', verbose_name='URL Central License Server')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Sudah Diaktifkan?')),
                ('last_validated', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Divalidasi')),
                ('validation_cache', models.BooleanField(default=False, verbose_name='Cache Validasi (Valid/Invalid)')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Cache Kedaluwarsa Pada')),
                ('validation_message', models.TextField(blank=True, null=True, verbose_name='Pesan Validasi Terakhir')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Produk')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Klien')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Lisensi Berakhir')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Kunci Maintenance (Dari CLS)')),
                ('maintenance_message', models.TextField(blank=True, null=True, verbose_name='Pesan Maintenance')),
                ('min_app_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimal Versi Aplikasi')),
                ('force_update_url', models.URLField(blank=True, null=True, verbose_name='URL Force Update')),
                ('app_version', models.CharField(default='v1.0', max_length=20, verbose_name='Versi Aplikasi Lokal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Lisensi',
                'verbose_name_plural': 'Konfigurasi Lisensi',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('module', models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('sparepart', 'Sparepart'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('kas_bank', 'Kas & Bank / Treasury'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('automation', 'Automasi Telegram'), ('access_control', 'Access Control'), ('ai_assistant', 'AI Manajemen'), ('fraud_detection', 'Fraud Detection'), ('service_center', 'Service Center'), ('akuntansi', 'Akuntansi'), ('laporan_keuangan', 'Laporan Keuangan'), ('piutang', 'Piutang (AR)'), ('hutang', 'Hutang (AP)'), ('aset', 'Aset Tetap'), ('pajak', 'Pajak (PPN)'), ('rekonsiliasi_keuangan', 'Rekonsiliasi Keuangan')], max_length=50, verbose_name='Module')),
                ('sub_module', models.CharField(blank=True, help_text="Specific page/feature within module (e.g., 'kategori', 'satuan', 'daftar_produk')", max_length=100, null=True, verbose_name='Sub Module')),
                ('can_view', models.BooleanField(default=True, help_text='Dapat melihat/membaca data', verbose_name='Can View')),
                ('can_create', models.BooleanField(default=False, help_text='Dapat menambah data baru', verbose_name='Can Create')),
                ('can_edit', models.BooleanField(default=False, help_text='Dapat mengubah data', verbose_name='Can Edit')),
                ('can_delete', models.BooleanField(default=False, help_text='Dapat menghapus data', verbose_name='Can Delete')),
                ('description', models.TextField(blank=True, help_text='Catatan tambahan tentang permission ini', null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role', 'module', 'sub_module'],
                'indexes': [models.Index(fields=['role', 'module', 'sub_module'], name='core_rp_role_mod_sub_idx'), models.Index(fields=['module', 'sub_module'], name='core_rp_mod_sub_idx')],
                'unique_together': {('role', 'module', 'sub_module')},
            },
        ),
    ]
