# Generated by Django 5.0.6 on 2026-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan')], max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser - Full Access'), ('ADMIN', 'Admin - Limited Access'), ('USER', 'User - Read & Create Only'), ('KASIR', 'Kasir - POS Access Only')], max_length=50, verbose_name='Role'),
        ),
    ]
