# Generated by Django 5.0.6 on 2026-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rolepermission_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Role'),
        ),
    ]
