# Generated by Django 5.0.6 on 2026-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_rolepermission_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ['role', 'module', 'sub_module'], 'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(blank=True, help_text='Sub-module/SubCRUD untuk permission granular (e.g., kategori, satuan, gudang)', max_length=100, null=True, verbose_name='Sub Module'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser - Full Access'), ('ADMIN', 'Admin - Limited Access'), ('USER', 'User - Read & Create Only'), ('KASIR', 'Kasir - POS Access Only')], max_length=50, verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'module', 'sub_module')},
        ),
    ]
