# Generated by Django 5.0.6 on 2026-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rolepermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='sub_module',
            field=models.CharField(blank=True, help_text="Specific page/feature within module (e.g., 'kategori', 'satuan', 'daftar_produk')", max_length=100, null=True, verbose_name='Sub Module'),
        ),
    ]
