# Generated by Django 5.0.6 on 2026-02-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_permission_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rolepermission',
            name='role_view_idx',
        ),
        migrations.RemoveIndex(
            model_name='rolepermission',
            name='module_sub_idx',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('access_control', 'Access Control')], max_length=50, verbose_name='Module'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Role'),
        ),
    ]
