# Generated by Django 6.0.3 on 2026-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rolepermission_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kunci Lisensi')),
                ('hardware_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hardware ID')),
                ('cls_server_url', models.URLField(default='https://cls.serpgroup.cloud', help_text='Alamat server CLS (contoh: https://cls.serpgroup.cloud)', verbose_name='URL Central License Server')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Sudah Diaktifkan?')),
                ('last_validated', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Divalidasi')),
                ('validation_cache', models.BooleanField(default=False, verbose_name='Cache Validasi (Valid/Invalid)')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Cache Kedaluwarsa Pada')),
                ('validation_message', models.TextField(blank=True, null=True, verbose_name='Pesan Validasi Terakhir')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Produk')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Klien')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Lisensi Berakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Lisensi',
                'verbose_name_plural': 'Konfigurasi Lisensi',
            },
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('automation', 'Automasi Telegram'), ('access_control', 'Access Control'), ('ai_assistant', 'AI Manajemen'), ('fraud_detection', 'Fraud Detection')], max_length=50, verbose_name='Module'),
        ),
    ]
