# Generated by Django 6.0.3 on 2026-04-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_license_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseconfig',
            name='app_version',
            field=models.CharField(default='v1.0', max_length=20, verbose_name='Versi Aplikasi Lokal'),
        ),
        migrations.AddField(
            model_name='licenseconfig',
            name='force_update_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Force Update'),
        ),
        migrations.AddField(
            model_name='licenseconfig',
            name='is_maintenance',
            field=models.BooleanField(default=False, verbose_name='Kunci Maintenance (Dari CLS)'),
        ),
        migrations.AddField(
            model_name='licenseconfig',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True, verbose_name='Pesan Maintenance'),
        ),
        migrations.AddField(
            model_name='licenseconfig',
            name='min_app_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimal Versi Aplikasi'),
        ),
    ]
