# Generated by Django 5.0.6 on 2026-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_licenseconfig_app_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('kas_bank', 'Kas & Bank / Treasury'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('automation', 'Automasi Telegram'), ('access_control', 'Access Control'), ('ai_assistant', 'AI Manajemen'), ('fraud_detection', 'Fraud Detection'), ('akuntansi', 'Akuntansi'), ('piutang', 'Piutang (AR)'), ('hutang', 'Hutang (AP)'), ('aset', 'Aset Tetap'), ('pajak', 'Pajak (PPN)')], max_length=50, verbose_name='Module'),
        ),
    ]
