# Generated by Django 6.0.3 on 2026-05-15 07:59

from django.db import migrations, models


REPORT_SUBMODULES = ('trial_balance', 'laba_rugi', 'neraca', 'arus_kas')


def move_financial_report_permissions_forward(apps, schema_editor):
    RolePermission = apps.get_model('core', 'RolePermission')
    role_flags = {}

    old_permissions = RolePermission.objects.filter(module='akuntansi', sub_module__in=REPORT_SUBMODULES)
    for old in old_permissions:
        flags = role_flags.setdefault(
            old.role,
            {'can_view': False, 'can_create': False, 'can_edit': False, 'can_delete': False},
        )
        flags['can_view'] = flags['can_view'] or old.can_view
        flags['can_create'] = flags['can_create'] or old.can_create
        flags['can_edit'] = flags['can_edit'] or old.can_edit
        flags['can_delete'] = flags['can_delete'] or old.can_delete

        target, created = RolePermission.objects.get_or_create(
            role=old.role,
            module='laporan_keuangan',
            sub_module=old.sub_module,
            defaults={
                'can_view': old.can_view,
                'can_create': old.can_create,
                'can_edit': old.can_edit,
                'can_delete': old.can_delete,
                'description': old.description,
            },
        )
        if not created:
            target.can_view = target.can_view or old.can_view
            target.can_create = target.can_create or old.can_create
            target.can_edit = target.can_edit or old.can_edit
            target.can_delete = target.can_delete or old.can_delete
            target.save(update_fields=['can_view', 'can_create', 'can_edit', 'can_delete', 'updated_at'])

    for role, flags in role_flags.items():
        target, created = RolePermission.objects.get_or_create(
            role=role,
            module='laporan_keuangan',
            sub_module=None,
            defaults={
                **flags,
                'description': f'Migrated financial statement module permission for {role}',
            },
        )
        if not created:
            target.can_view = target.can_view or flags['can_view']
            target.can_create = target.can_create or flags['can_create']
            target.can_edit = target.can_edit or flags['can_edit']
            target.can_delete = target.can_delete or flags['can_delete']
            target.save(update_fields=['can_view', 'can_create', 'can_edit', 'can_delete', 'updated_at'])

    old_permissions.delete()


def move_financial_report_permissions_backward(apps, schema_editor):
    RolePermission = apps.get_model('core', 'RolePermission')
    report_permissions = RolePermission.objects.filter(module='laporan_keuangan', sub_module__in=REPORT_SUBMODULES)

    for report in report_permissions:
        target, created = RolePermission.objects.get_or_create(
            role=report.role,
            module='akuntansi',
            sub_module=report.sub_module,
            defaults={
                'can_view': report.can_view,
                'can_create': report.can_create,
                'can_edit': report.can_edit,
                'can_delete': report.can_delete,
                'description': report.description,
            },
        )
        if not created:
            target.can_view = target.can_view or report.can_view
            target.can_create = target.can_create or report.can_create
            target.can_edit = target.can_edit or report.can_edit
            target.can_delete = target.can_delete or report.can_delete
            target.save(update_fields=['can_view', 'can_create', 'can_edit', 'can_delete', 'updated_at'])

    RolePermission.objects.filter(module='laporan_keuangan').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_kas_bank_module_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('kas_bank', 'Kas & Bank / Treasury'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('automation', 'Automasi Telegram'), ('access_control', 'Access Control'), ('ai_assistant', 'AI Manajemen'), ('fraud_detection', 'Fraud Detection'), ('akuntansi', 'Akuntansi'), ('laporan_keuangan', 'Laporan Keuangan'), ('piutang', 'Piutang (AR)'), ('hutang', 'Hutang (AP)'), ('aset', 'Aset Tetap'), ('pajak', 'Pajak (PPN)')], max_length=50, verbose_name='Module'),
        ),
        migrations.RunPython(
            move_financial_report_permissions_forward,
            move_financial_report_permissions_backward,
        ),
    ]
