# Generated by Django 6.0.3 on 2026-05-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_rolepermission_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseConfig',
        ),
    ]
