# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_rekonsiliasi_keuangan_permissions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'module', 'sub_module'], name='core_rp_role_mod_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['module', 'sub_module'], name='core_rp_mod_sub_idx'),
        ),
    ]
