# Generated by Django 6.0.3 on 2026-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kunci Lisensi')),
                ('hardware_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hardware ID')),
                ('cls_server_url', models.URLField(default='https://cls.serpgroup.cloud', help_text='Alamat server CLS (contoh: https://cls.serpgroup.cloud)', verbose_name='URL Central License Server')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Sudah Diaktifkan?')),
                ('last_validated', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Divalidasi')),
                ('validation_cache', models.BooleanField(default=False, verbose_name='Cache Validasi (Valid/Invalid)')),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Cache Kedaluwarsa Pada')),
                ('validation_message', models.TextField(blank=True, null=True, verbose_name='Pesan Validasi Terakhir')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Produk')),
                ('client_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Klien')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Lisensi Berakhir')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Kunci Maintenance (Dari CLS)')),
                ('maintenance_message', models.TextField(blank=True, null=True, verbose_name='Pesan Maintenance')),
                ('min_app_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='Minimal Versi Aplikasi')),
                ('force_update_url', models.URLField(blank=True, null=True, verbose_name='URL Force Update')),
                ('app_version', models.CharField(default='v1.0', max_length=20, verbose_name='Versi Aplikasi Lokal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Lisensi',
                'verbose_name_plural': 'Konfigurasi Lisensi',
            },
        ),
    ]
