# Generated by Django 6.0.3 on 2026-06-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_service_center_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('kas_bank', 'Kas & Bank / Treasury'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('automation', 'Automasi Telegram'), ('access_control', 'Access Control'), ('ai_assistant', 'AI Manajemen'), ('fraud_detection', 'Fraud Detection'), ('akuntansi', 'Akuntansi'), ('laporan_keuangan', 'Laporan Keuangan'), ('piutang', 'Piutang (AR)'), ('hutang', 'Hutang (AP)'), ('aset', 'Aset Tetap'), ('pajak', 'Pajak (PPN)'), ('rekonsiliasi_keuangan', 'Rekonsiliasi Keuangan'), ('service_center', 'Service Center'), ('sparepart', 'Sparepart')], max_length=50, verbose_name='Module'),
        ),
    ]
