# Generated by Django 6.0.3 on 2026-06-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseconfig',
            name='circuit_open_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Circuit Breaker Buka Sampai'),
        ),
        migrations.AddField(
            model_name='licenseconfig',
            name='consecutive_failures',
            field=models.IntegerField(default=0, verbose_name='Gagal Beruntun (Circuit Breaker)'),
        ),
        migrations.AddField(
            model_name='licenseconfig',
            name='offline_warning_dismissed',
            field=models.BooleanField(default=False, verbose_name='Peringatan Offline Dismissed'),
        ),
    ]
