# Generated by Django 6.0.3 on 2026-07-22 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_licenseconfig_circuit_open_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('produk', 'Produk'), ('inventory', 'Inventory'), ('pembelian', 'Pembelian'), ('penjualan', 'Penjualan'), ('pos', 'POS / Kasir'), ('kas_bank', 'Kas & Bank / Treasury'), ('biaya', 'Biaya'), ('laporan', 'Laporan'), ('hr', 'HR / Human Resource'), ('user_management', 'User Management'), ('activity_log', 'Log Aktivitas'), ('pengaturan', 'Pengaturan'), ('automation', 'Automasi Telegram'), ('access_control', 'Access Control'), ('ai_assistant', 'AI Manajemen'), ('fraud_detection', 'Fraud Detection'), ('akuntansi', 'Akuntansi'), ('laporan_keuangan', 'Laporan Keuangan'), ('piutang', 'Piutang (AR)'), ('hutang', 'Hutang (AP)'), ('aset', 'Aset Tetap'), ('pajak', 'Pajak (PPN)'), ('rekonsiliasi_keuangan', 'Rekonsiliasi Keuangan')], max_length=50, verbose_name='Module'),
        ),
        migrations.CreateModel(
            name='UserModuleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Read Timestamp',
                'verbose_name_plural': 'Module Read Timestamps',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
