# Generated by Django 6.0.3 on 2026-07-21 10:33

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biaya', '0007_alter_transaksibiaya_bukti'),
        ('pos', '0012_alter_metodepembayaran_gambar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimburseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True, verbose_name='Nomor Reimburse')),
                ('tanggal', models.DateField(verbose_name='Tanggal Pengajuan')),
                ('keterangan', models.TextField(verbose_name='Keterangan')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Reimburse')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('paid', 'Dibayar'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Disetujui')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Alasan Penolakan')),
                ('tanggal_bayar', models.DateField(blank=True, null=True, verbose_name='Tanggal Bayar')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Dibatalkan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimburse_disetujui', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimburse_dibatalkan', to=settings.AUTH_USER_MODEL, verbose_name='Dibatalkan Oleh')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimburse_dibuat', to=settings.AUTH_USER_MODEL)),
                ('metode_pembayaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_reimburse', to='pos.metodepembayaran', verbose_name='Metode Pembayaran')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimburse_diajukan', to=settings.AUTH_USER_MODEL, verbose_name='Pemohon')),
            ],
            options={
                'verbose_name': 'Reimburse',
                'verbose_name_plural': 'Reimburse',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='ReimburseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=255, verbose_name='Deskripsi')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nominal')),
                ('bukti', models.FileField(blank=True, null=True, upload_to='reimburse/bukti/', validators=[apps.core.validators.validate_expense_proof], verbose_name='Bukti (Foto/PDF)')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_reimburse', to='biaya.kategoribiaya', verbose_name='Kategori')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reimburse.reimburserequest', verbose_name='Pengajuan')),
            ],
            options={
                'verbose_name': 'Item Reimburse',
                'verbose_name_plural': 'Item Reimburse',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='reimburserequest',
            index=models.Index(fields=['tanggal', 'status'], name='rmb_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reimburserequest',
            index=models.Index(fields=['pemohon', 'status'], name='rmb_pemohon_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reimburserequest',
            index=models.Index(fields=['status'], name='rmb_status_idx'),
        ),
    ]
