# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PembayaranPPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True, verbose_name='Nomor Setor')),
                ('tipe', models.CharField(choices=[('setor', 'Setor (Kurang Bayar)'), ('restitusi', 'Restitusi (Lebih Bayar)')], default='setor', max_length=15, verbose_name='Tipe')),
                ('masa_bulan', models.IntegerField(help_text='1-12', verbose_name='Masa Bulan')),
                ('masa_tahun', models.IntegerField(verbose_name='Masa Tahun')),
                ('total_ppn_keluaran', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total PPN Keluaran')),
                ('total_ppn_masukan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total PPN Masukan')),
                ('jumlah_setor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Setor / Restitusi')),
                ('tanggal_setor', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Setor')),
                ('nomor_bukti', models.CharField(blank=True, default='', help_text='Nomor bukti setor pajak (NTPN) jika ada', max_length=80, verbose_name='No. Bukti / NTPN')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pembayaran PPN',
                'verbose_name_plural': 'Pembayaran PPN',
                'ordering': ['-tanggal_setor', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='SettingPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_ppn', models.DecimalField(decimal_places=2, default=11.0, help_text='Tarif PPN Indonesia saat ini: 11%', max_digits=5, verbose_name='Tarif PPN (%)')),
                ('npwp', models.CharField(blank=True, default='', max_length=30, verbose_name='NPWP Perusahaan')),
                ('nama_pkp', models.CharField(blank=True, default='', max_length=200, verbose_name='Nama PKP')),
                ('alamat_pkp', models.TextField(blank=True, default='', verbose_name='Alamat PKP')),
                ('is_pkp', models.BooleanField(default=False, help_text='Jika PKP, wajib pungut PPN', verbose_name='Terdaftar PKP?')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting Pajak',
                'verbose_name_plural': 'Setting Pajak',
            },
        ),
        migrations.CreateModel(
            name='FakturPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_seri', models.CharField(max_length=50, unique=True, verbose_name='Nomor Seri Faktur')),
                ('tipe', models.CharField(choices=[('masukan', 'PPN Masukan (Pembelian)'), ('keluaran', 'PPN Keluaran (Penjualan)')], max_length=10, verbose_name='Tipe Faktur')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Faktur')),
                ('dpp', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='DPP (Dasar Pengenaan Pajak)')),
                ('tarif_ppn', models.DecimalField(decimal_places=2, default=11.0, max_digits=5, verbose_name='Tarif PPN (%)')),
                ('ppn', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPN')),
                ('nama_lawan', models.CharField(max_length=200, verbose_name='Nama Lawan Transaksi')),
                ('npwp_lawan', models.CharField(blank=True, default='', max_length=30, verbose_name='NPWP Lawan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Disetujui'), ('reported', 'Dilaporkan'), ('batal', 'Dibatalkan')], default='draft', max_length=10, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Faktur Pajak',
                'verbose_name_plural': 'Faktur Pajak',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
