# Generated by Django 6.0.3 on 2026-05-09 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pembelian', '0004_purchaseorderitem_jumlah_konversi_and_more'),
        ('penjualan', '0004_salesorderitem_jumlah_konversi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_ppn', models.DecimalField(decimal_places=2, default=11.0, help_text='Tarif PPN Indonesia saat ini: 11%', max_digits=5, verbose_name='Tarif PPN (%)')),
                ('npwp', models.CharField(blank=True, default='', max_length=30, verbose_name='NPWP Perusahaan')),
                ('nama_pkp', models.CharField(blank=True, default='', max_length=200, verbose_name='Nama PKP')),
                ('alamat_pkp', models.TextField(blank=True, default='', verbose_name='Alamat PKP')),
                ('is_pkp', models.BooleanField(default=False, help_text='Jika PKP, wajib pungut PPN', verbose_name='Terdaftar PKP?')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting Pajak',
                'verbose_name_plural': 'Setting Pajak',
            },
        ),
        migrations.CreateModel(
            name='FakturPajak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_seri', models.CharField(max_length=50, unique=True, verbose_name='Nomor Seri Faktur')),
                ('tipe', models.CharField(choices=[('masukan', 'PPN Masukan (Pembelian)'), ('keluaran', 'PPN Keluaran (Penjualan)')], max_length=10, verbose_name='Tipe Faktur')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Faktur')),
                ('dpp', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='DPP (Dasar Pengenaan Pajak)')),
                ('tarif_ppn', models.DecimalField(decimal_places=2, default=11.0, max_digits=5, verbose_name='Tarif PPN (%)')),
                ('ppn', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPN')),
                ('nama_lawan', models.CharField(max_length=200, verbose_name='Nama Lawan Transaksi')),
                ('npwp_lawan', models.CharField(blank=True, default='', max_length=30, verbose_name='NPWP Lawan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Disetujui'), ('reported', 'Dilaporkan'), ('batal', 'Dibatalkan')], default='draft', max_length=10, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur_pajak_set', to='pembelian.purchaseorder', verbose_name='Purchase Order')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur_pajak_set', to='penjualan.salesorder', verbose_name='Sales Order')),
            ],
            options={
                'verbose_name': 'Faktur Pajak',
                'verbose_name_plural': 'Faktur Pajak',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
