# Generated by Django 6.0.3 on 2026-05-14 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0003_alter_akun_sub_tipe_alter_jurnalentry_sumber'),
        ('pajak', '0001_initial'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PembayaranPPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=50, unique=True, verbose_name='Nomor Setor')),
                ('tipe', models.CharField(choices=[('setor', 'Setor (Kurang Bayar)'), ('restitusi', 'Restitusi (Lebih Bayar)')], default='setor', max_length=15, verbose_name='Tipe')),
                ('masa_bulan', models.IntegerField(help_text='1-12', verbose_name='Masa Bulan')),
                ('masa_tahun', models.IntegerField(verbose_name='Masa Tahun')),
                ('total_ppn_keluaran', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total PPN Keluaran')),
                ('total_ppn_masukan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total PPN Masukan')),
                ('jumlah_setor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Setor / Restitusi')),
                ('tanggal_setor', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Setor')),
                ('nomor_bukti', models.CharField(blank=True, default='', help_text='Nomor bukti setor pajak (NTPN) jika ada', max_length=80, verbose_name='No. Bukti / NTPN')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('jurnal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_ppn', to='akuntansi.jurnalentry', verbose_name='Jurnal Entry')),
                ('metode_pembayaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.metodepembayaran', verbose_name='Metode Pembayaran')),
            ],
            options={
                'verbose_name': 'Pembayaran PPN',
                'verbose_name_plural': 'Pembayaran PPN',
                'ordering': ['-tanggal_setor', '-dibuat_pada'],
                'unique_together': {('masa_bulan', 'masa_tahun')},
            },
        ),
    ]
