# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0002_initial'),
        ('pajak', '0001_initial'),
        ('pembelian', '0001_initial'),
        ('penjualan', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturpajak',
            name='pos_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur_pajak_set', to='pos.postransaction', verbose_name='Transaksi POS'),
        ),
        migrations.AddField(
            model_name='fakturpajak',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur_pajak_set', to='pembelian.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='fakturpajak',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur_pajak_set', to='penjualan.salesorder', verbose_name='Sales Order'),
        ),
        migrations.AddField(
            model_name='pembayaranppn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='pembayaranppn',
            name='jurnal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_ppn', to='akuntansi.jurnalentry', verbose_name='Jurnal Entry'),
        ),
        migrations.AddField(
            model_name='pembayaranppn',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['tanggal', 'tipe', 'status'], name='tax_faktur_tgl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['sales_order', 'tipe'], name='tax_faktur_so_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['purchase_order', 'tipe'], name='tax_faktur_po_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['pos_transaction', 'tipe'], name='tax_faktur_pos_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranppn',
            index=models.Index(fields=['masa_tahun', 'masa_bulan'], name='tax_ppn_masa_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranppn',
            index=models.Index(fields=['tanggal_setor', 'tipe'], name='tax_ppn_tgl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranppn',
            index=models.Index(fields=['metode_pembayaran', 'tanggal_setor'], name='tax_ppn_metode_tgl_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pembayaranppn',
            unique_together={('masa_bulan', 'masa_tahun')},
        ),
    ]
