# Generated by Django 6.0.3 on 2026-05-15 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pajak', '0002_pembayaranppn'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakturpajak',
            name='pos_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur_pajak_set', to='pos.postransaction', verbose_name='Transaksi POS'),
        ),
    ]
