# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
        ('pajak', '0003_fakturpajak_pos_transaction'),
        ('pembelian', '0004_purchaseorderitem_jumlah_konversi_and_more'),
        ('penjualan', '0004_salesorderitem_jumlah_konversi_and_more'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['tanggal', 'tipe', 'status'], name='tax_faktur_tgl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['sales_order', 'tipe'], name='tax_faktur_so_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['purchase_order', 'tipe'], name='tax_faktur_po_type_idx'),
        ),
        migrations.AddIndex(
            model_name='fakturpajak',
            index=models.Index(fields=['pos_transaction', 'tipe'], name='tax_faktur_pos_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranppn',
            index=models.Index(fields=['masa_tahun', 'masa_bulan'], name='tax_ppn_masa_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranppn',
            index=models.Index(fields=['tanggal_setor', 'tipe'], name='tax_ppn_tgl_type_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranppn',
            index=models.Index(fields=['metode_pembayaran', 'tanggal_setor'], name='tax_ppn_metode_tgl_idx'),
        ),
    ]
