# Generated by Django 5.0.6 on 2026-01-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Gudang')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Gudang')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gudang',
                'verbose_name_plural': 'Gudang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Satuan')),
                ('singkatan', models.CharField(max_length=10, verbose_name='Singkatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Satuan',
                'verbose_name_plural': 'Satuan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategori_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Beli')),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Jual')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/', verbose_name='Gambar Produk')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='produk.kategori', verbose_name='Kategori')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='produk.satuan', verbose_name='Satuan')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_set', to='produk.gudang', verbose_name='Gudang')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_set', to='produk.produk', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stok',
                'ordering': ['produk', 'gudang'],
                'unique_together': {('produk', 'gudang')},
            },
        ),
    ]
