# Generated by Django 5.0.6 on 2026-06-02 01:08

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Satuan')),
                ('singkatan', models.CharField(max_length=10, verbose_name='Singkatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Satuan',
                'verbose_name_plural': 'Satuan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Gudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Gudang')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Gudang')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('pajak_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pajak (%)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('metode_pembayaran_default', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gudang_default', to='pos.metodepembayaran', verbose_name='Metode Pembayaran Default')),
            ],
            options={
                'verbose_name': 'Gudang',
                'verbose_name_plural': 'Gudang',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategori_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barcode')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Produk')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('harga_beli', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Beli')),
                ('harga_jual', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Jual')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar Produk')),
                ('tipe', models.CharField(choices=[('produk', 'Produk'), ('sparepart', 'Sparepart')], default='produk', help_text='Produk untuk penjualan umum, Sparepart untuk service center', max_length=15, verbose_name='Tipe')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('kena_ppn', models.BooleanField(default=True, help_text='Jika dicentang, produk ini akan dikenakan PPN saat transaksi', verbose_name='Kena PPN')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_cabang', to='produk.gudang', verbose_name='Cabang')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk', to='produk.kategori', verbose_name='Kategori')),
                ('metode_pembayaran', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_set', to='pos.metodepembayaran', verbose_name='Metode Pembayaran')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produk', to='produk.satuan', verbose_name='Satuan')),
            ],
            options={
                'verbose_name': 'Produk',
                'verbose_name_plural': 'Produk',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='KonversiSatuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faktor_konversi', models.DecimalField(decimal_places=4, help_text='1 [dari_satuan] = ? [ke_satuan]', max_digits=15, verbose_name='Faktor Konversi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('produk', models.ForeignKey(blank=True, help_text='Kosongkan untuk konversi global, isi untuk override per produk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konversi_satuan', to='produk.produk', verbose_name='Produk (Opsional)')),
                ('dari_satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konversi_dari', to='produk.satuan', verbose_name='Dari Satuan')),
                ('ke_satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konversi_ke', to='produk.satuan', verbose_name='Ke Satuan')),
            ],
            options={
                'verbose_name': 'Konversi Satuan',
                'verbose_name_plural': 'Konversi Satuan',
                'ordering': ['dari_satuan', 'ke_satuan'],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah')),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_set', to='produk.gudang', verbose_name='Gudang')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stok_set', to='produk.produk', verbose_name='Produk')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stok',
                'ordering': ['produk', 'gudang'],
            },
        ),
        migrations.AddIndex(
            model_name='gudang',
            index=models.Index(fields=['aktif', 'nama'], name='gudang_aktif_nama_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['aktif', 'dibuat_pada'], name='prd_aktif_created_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['kategori', 'aktif'], name='prd_kat_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['cabang', 'aktif'], name='prd_cabang_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['metode_pembayaran', 'aktif'], name='prd_pay_aktif_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='konversisatuan',
            unique_together={('dari_satuan', 'ke_satuan', 'produk')},
        ),
        migrations.AddIndex(
            model_name='stok',
            index=models.Index(fields=['gudang', 'produk'], name='stok_gudang_produk_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stok',
            unique_together={('produk', 'gudang')},
        ),
    ]
