# Generated by Django 5.0.6 on 2026-01-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_cabang', to='produk.gudang', verbose_name='Cabang'),
        ),
    ]
