# Generated by Django 5.0.6 on 2026-02-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_produk_cabang'),
    ]

    operations = [
        migrations.AddField(
            model_name='gudang',
            name='pajak_persen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pajak (%)'),
        ),
    ]
