# Generated by Django 5.0.6 on 2026-02-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_add_saldo_to_metode'),
        ('produk', '0003_add_pajak_to_gudang'),
    ]

    operations = [
        migrations.AddField(
            model_name='gudang',
            name='metode_pembayaran_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gudang_default', to='pos.metodepembayaran', verbose_name='Metode Pembayaran Default'),
        ),
    ]
