# Generated by Django 5.0.6 on 2026-03-01 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_gudang_metode_pembayaran_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='KonversiSatuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faktor_konversi', models.DecimalField(decimal_places=4, help_text='1 [dari_satuan] = ? [ke_satuan]', max_digits=15, verbose_name='Faktor Konversi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dari_satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konversi_dari', to='produk.satuan', verbose_name='Dari Satuan')),
                ('ke_satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konversi_ke', to='produk.satuan', verbose_name='Ke Satuan')),
                ('produk', models.ForeignKey(blank=True, help_text='Kosongkan untuk konversi global, isi untuk override per produk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konversi_satuan', to='produk.produk', verbose_name='Produk (Opsional)')),
            ],
            options={
                'verbose_name': 'Konversi Satuan',
                'verbose_name_plural': 'Konversi Satuan',
                'ordering': ['dari_satuan', 'ke_satuan'],
                'unique_together': {('dari_satuan', 'ke_satuan', 'produk')},
            },
        ),
    ]
