# Generated by Django 6.0.3 on 2026-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_konversisatuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='tipe',
            field=models.CharField(choices=[('produk', 'Produk'), ('sparepart', 'Sparepart')], default='produk', help_text='Produk untuk penjualan umum, Sparepart untuk service center', max_length=15, verbose_name='Tipe'),
        ),
    ]
