# Generated by Django 6.0.3 on 2026-04-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_add_customer_fk'),
        ('produk', '0006_add_tipe_to_produk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produk_set', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
    ]
