# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_performance_indexes'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gudang',
            index=models.Index(fields=['aktif', 'nama'], name='gudang_aktif_nama_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['aktif', 'dibuat_pada'], name='prd_aktif_created_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['kategori', 'aktif'], name='prd_kat_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['cabang', 'aktif'], name='prd_cabang_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='produk',
            index=models.Index(fields=['metode_pembayaran', 'aktif'], name='prd_pay_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='stok',
            index=models.Index(fields=['gudang', 'produk'], name='stok_gudang_produk_idx'),
        ),
    ]
