# Generated by Django 6.0.3 on 2026-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_produk_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='kena_ppn',
            field=models.BooleanField(default=True, help_text='Jika dicentang, produk ini akan dikenakan PPN saat transaksi', verbose_name='Kena PPN'),
        ),
    ]
