# Generated by Django 6.0.3 on 2026-05-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_performance_indexes'),
        ('produk', '0007_produk_kena_ppn'),
    ]

    operations = [
    ]
