# Generated by Django 6.0.3 on 2026-05-22 09:16

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0008_merge_0007_performance_indexes_0007_produk_kena_ppn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar Produk'),
        ),
    ]
