# Generated by Django 6.0.3 on 2026-06-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0009_alter_produk_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='tipe',
            field=models.CharField(choices=[('produk', 'Produk'), ('sparepart', 'Sparepart')], default='produk', help_text='Produk untuk penjualan umum, Sparepart untuk service center', max_length=15, verbose_name='Tipe'),
        ),
    ]
