# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transfer', models.CharField(max_length=50, unique=True, verbose_name='Nomor Transfer')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer Stok',
                'verbose_name_plural': 'Transfer Stok',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='TransferStokItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('catatan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Catatan')),
            ],
            options={
                'verbose_name': 'Item Transfer',
                'verbose_name_plural': 'Item Transfer',
            },
        ),
        migrations.CreateModel(
            name='AdjustmentStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_adjustment', models.CharField(max_length=50, unique=True, verbose_name='Nomor Adjustment')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('tipe', models.CharField(choices=[('in', 'Penambahan'), ('out', 'Pengurangan')], max_length=10, verbose_name='Tipe')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('alasan', models.TextField(verbose_name='Alasan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjustment Stok',
                'verbose_name_plural': 'Adjustment Stok',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
