# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentstok',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.gudang', verbose_name='Gudang'),
        ),
        migrations.AddField(
            model_name='adjustmentstok',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk', verbose_name='Produk'),
        ),
        migrations.AddField(
            model_name='transferstok',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferstok',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferstok',
            name='gudang_asal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_keluar', to='produk.gudang', verbose_name='Gudang Asal'),
        ),
        migrations.AddField(
            model_name='transferstok',
            name='gudang_tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_masuk', to='produk.gudang', verbose_name='Gudang Tujuan'),
        ),
        migrations.AddField(
            model_name='transferstokitem',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk', verbose_name='Produk'),
        ),
        migrations.AddField(
            model_name='transferstokitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transferstok', verbose_name='Transfer'),
        ),
        migrations.AddIndex(
            model_name='adjustmentstok',
            index=models.Index(fields=['tanggal', 'tipe'], name='inv_adj_tgl_tipe_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmentstok',
            index=models.Index(fields=['produk', 'gudang'], name='inv_adj_prod_gdg_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmentstok',
            index=models.Index(fields=['gudang', 'tanggal'], name='inv_adj_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstok',
            index=models.Index(fields=['status', 'dibuat_pada'], name='inv_trf_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstok',
            index=models.Index(fields=['gudang_asal', 'status'], name='inv_trf_asal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstok',
            index=models.Index(fields=['gudang_tujuan', 'status'], name='inv_trf_tujuan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstokitem',
            index=models.Index(fields=['produk', 'transfer'], name='inv_item_prod_trf_idx'),
        ),
    ]
