# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adjustmentstok',
            index=models.Index(fields=['tanggal', 'tipe'], name='inv_adj_tgl_tipe_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmentstok',
            index=models.Index(fields=['produk', 'gudang'], name='inv_adj_prod_gdg_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmentstok',
            index=models.Index(fields=['gudang', 'tanggal'], name='inv_adj_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstok',
            index=models.Index(fields=['status', 'dibuat_pada'], name='inv_trf_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstok',
            index=models.Index(fields=['gudang_asal', 'status'], name='inv_trf_asal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstok',
            index=models.Index(fields=['gudang_tujuan', 'status'], name='inv_trf_tujuan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transferstokitem',
            index=models.Index(fields=['produk', 'transfer'], name='inv_item_prod_trf_idx'),
        ),
    ]
