# Generated by Django 5.0.6 on 2026-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(choices=[('pos', 'Transaksi POS'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('biaya', 'Transaksi Biaya')], max_length=30, verbose_name='Jenis Transaksi')),
                ('nomor_referensi', models.CharField(max_length=100, verbose_name='Nomor Referensi')),
                ('pesan', models.TextField(verbose_name='Pesan yang Dikirim')),
                ('status', models.CharField(choices=[('sukses', 'Sukses'), ('gagal', 'Gagal')], max_length=10, verbose_name='Status')),
                ('respons', models.TextField(blank=True, null=True, verbose_name='Respons API')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Pesan Error')),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim Pada')),
            ],
            options={
                'verbose_name': 'Log Notifikasi',
                'verbose_name_plural': 'Log Notifikasi',
                'ordering': ['-dikirim_pada'],
            },
        ),
        migrations.CreateModel(
            name='PengaturanTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='Token dari @BotFather, contoh: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11', max_length=200, verbose_name='Bot Token')),
                ('chat_id', models.CharField(blank=True, help_text='Chat ID tujuan (grup atau personal). Gunakan @userinfobot untuk mengetahui Chat ID', max_length=100, verbose_name='Chat ID')),
                ('aktif', models.BooleanField(default=False, verbose_name='Aktif')),
                ('notif_pos', models.BooleanField(default=True, verbose_name='Notifikasi Transaksi POS')),
                ('notif_sales_order', models.BooleanField(default=True, verbose_name='Notifikasi Sales Order')),
                ('notif_purchase_order', models.BooleanField(default=True, verbose_name='Notifikasi Purchase Order')),
                ('notif_biaya', models.BooleanField(default=True, verbose_name='Notifikasi Transaksi Biaya')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Telegram',
                'verbose_name_plural': 'Pengaturan Telegram',
            },
        ),
        migrations.CreateModel(
            name='TemplatePesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('pos', 'Transaksi POS'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('biaya', 'Transaksi Biaya')], max_length=30, unique=True, verbose_name='Jenis Transaksi')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('template_pesan', models.TextField(help_text='Gunakan variabel dalam kurung kurawal ganda, contoh: {{nomor_transaksi}}', verbose_name='Template Pesan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Pesan',
                'verbose_name_plural': 'Template Pesan',
                'ordering': ['jenis'],
            },
        ),
    ]
