# Generated by Django 6.0.3 on 2026-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturantelegram',
            name='kirim_pdf',
            field=models.BooleanField(default=True, help_text='Jika aktif, setiap notifikasi juga akan mengirim file PDF dokumen ke Telegram', verbose_name='Kirim PDF Otomatis'),
        ),
        migrations.AddField(
            model_name='pengaturantelegram',
            name='notif_penggajian',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Slip Gaji'),
        ),
        migrations.AlterField(
            model_name='lognotifikasi',
            name='jenis_transaksi',
            field=models.CharField(choices=[('pos', 'Transaksi POS'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('biaya', 'Transaksi Biaya'), ('penggajian', 'Slip Gaji')], max_length=30, verbose_name='Jenis Transaksi'),
        ),
        migrations.AlterField(
            model_name='templatepesan',
            name='jenis',
            field=models.CharField(choices=[('pos', 'Transaksi POS'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('biaya', 'Transaksi Biaya'), ('penggajian', 'Slip Gaji')], max_length=30, unique=True, verbose_name='Jenis Transaksi'),
        ),
    ]
