# Generated by Django 6.0.3 on 2026-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_add_system_prompt_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturantelegram',
            name='notif_service_order',
            field=models.BooleanField(default=True, verbose_name='Notifikasi Order Service'),
        ),
        migrations.AlterField(
            model_name='lognotifikasi',
            name='jenis_transaksi',
            field=models.CharField(choices=[('pos', 'Transaksi POS'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('biaya', 'Transaksi Biaya'), ('penggajian', 'Slip Gaji'), ('order_service', 'Order Service')], max_length=30, verbose_name='Jenis Transaksi'),
        ),
        migrations.AlterField(
            model_name='templatepesan',
            name='jenis',
            field=models.CharField(choices=[('pos', 'Transaksi POS'), ('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order'), ('biaya', 'Transaksi Biaya'), ('penggajian', 'Slip Gaji'), ('order_service', 'Order Service')], max_length=30, unique=True, verbose_name='Jenis Transaksi'),
        ),
    ]
