# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penjualan', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='produk.gudang', verbose_name='Gudang'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk', verbose_name='Produk'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='penjualan.salesorder', verbose_name='Sales Order'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='satuan_transaksi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika menggunakan satuan asli produk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.satuan', verbose_name='Satuan Transaksi'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tanggal', 'status'], name='sales_so_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', 'status'], name='sales_so_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['gudang', 'tanggal'], name='sales_so_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='sales_so_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['produk', 'sales_order'], name='sales_item_prod_so_idx'),
        ),
    ]
