# Generated by Django 5.0.6 on 2026-02-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0002_alter_salesorder_tanggal'),
        ('pos', '0004_add_saldo_to_metode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
    ]
