# Generated by Django 5.0.6 on 2026-03-01 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0003_salesorder_metode_pembayaran'),
        ('produk', '0005_konversisatuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='jumlah_konversi',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Jumlah dalam satuan dasar produk, dihitung otomatis', max_digits=15, verbose_name='Jumlah (Satuan Dasar)'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='satuan_transaksi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika menggunakan satuan asli produk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.satuan', verbose_name='Satuan Transaksi'),
        ),
    ]
