# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0004_salesorderitem_jumlah_konversi_and_more'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['aktif', 'nama'], name='sales_cust_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tanggal', 'status'], name='sales_so_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', 'status'], name='sales_so_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['gudang', 'tanggal'], name='sales_so_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='sales_so_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderitem',
            index=models.Index(fields=['produk', 'sales_order'], name='sales_item_prod_so_idx'),
        ),
    ]
