# Generated by Django 5.0.6 on 2026-01-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Tambah Data'), ('update', 'Edit Data'), ('delete', 'Hapus Data'), ('view', 'Lihat Data'), ('export', 'Export Data'), ('import', 'Import Data'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20, verbose_name='Aksi')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Object')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Perubahan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_0431e5_idx'), models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_86fd57_idx'), models.Index(fields=['action', '-timestamp'], name='activity_lo_action_01530e_idx')],
            },
        ),
    ]
