# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Tambah Data'), ('update', 'Edit Data'), ('delete', 'Hapus Data'), ('view', 'Lihat Data'), ('export', 'Export Data'), ('import', 'Import Data'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Batalkan'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_adjustment', 'Penyesuaian Stok'), ('stock_transfer_in', 'Transfer Masuk'), ('stock_transfer_out', 'Transfer Keluar')], max_length=20, verbose_name='Aksi')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Object')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Perubahan')),
                ('source_type', models.CharField(blank=True, choices=[('purchase', 'Pembelian (PO)'), ('sales', 'Penjualan (SO)'), ('pos', 'Point of Sale'), ('transfer', 'Transfer Stok'), ('adjustment', 'Adjustment'), ('manual', 'Input Manual')], max_length=20, null=True, verbose_name='Sumber')),
                ('source_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Sumber')),
                ('source_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Referensi Sumber')),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Qty Sebelum')),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Qty Sesudah')),
                ('quantity_change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Perubahan Qty')),
                ('gudang_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Gudang')),
                ('gudang_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Gudang')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_0431e5_idx'), models.Index(fields=['user', '-timestamp'], name='activity_lo_user_id_86fd57_idx'), models.Index(fields=['action', '-timestamp'], name='activity_lo_action_01530e_idx'), models.Index(fields=['model_name', 'object_id'], name='activity_lo_model_n_ca69bd_idx'), models.Index(fields=['source_type', '-timestamp'], name='activity_lo_source__81fd60_idx')],
            },
        ),
    ]
