# Generated by Django 5.0.6 on 2026-02-01 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='gudang_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Gudang'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='gudang_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Gudang'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='quantity_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Qty Sesudah'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='quantity_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Qty Sebelum'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='quantity_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Perubahan Qty'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Sumber'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='source_repr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Referensi Sumber'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='source_type',
            field=models.CharField(blank=True, choices=[('purchase', 'Pembelian (PO)'), ('sales', 'Penjualan (SO)'), ('pos', 'Point of Sale'), ('transfer', 'Transfer Stok'), ('adjustment', 'Adjustment'), ('manual', 'Input Manual')], max_length=20, null=True, verbose_name='Sumber'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Tambah Data'), ('update', 'Edit Data'), ('delete', 'Hapus Data'), ('view', 'Lihat Data'), ('export', 'Export Data'), ('import', 'Import Data'), ('approve', 'Approve'), ('reject', 'Reject'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_adjustment', 'Penyesuaian Stok'), ('stock_transfer_in', 'Transfer Masuk'), ('stock_transfer_out', 'Transfer Keluar')], max_length=20, verbose_name='Aksi'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['model_name', 'object_id'], name='activity_lo_model_n_ca69bd_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['source_type', '-timestamp'], name='activity_lo_source__81fd60_idx'),
        ),
    ]
