# Generated by Django 6.0.3 on 2026-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_enhance_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Tambah Data'), ('update', 'Edit Data'), ('delete', 'Hapus Data'), ('view', 'Lihat Data'), ('export', 'Export Data'), ('import', 'Import Data'), ('approve', 'Approve'), ('reject', 'Reject'), ('cancel', 'Batalkan'), ('stock_in', 'Stok Masuk'), ('stock_out', 'Stok Keluar'), ('stock_adjustment', 'Penyesuaian Stok'), ('stock_transfer_in', 'Transfer Masuk'), ('stock_transfer_out', 'Transfer Keluar')], max_length=20, verbose_name='Aksi'),
        ),
    ]
