# Generated by Django 5.0.6 on 2026-06-02 01:08

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jam_masuk', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('jam_keluar', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha'), ('cuti', 'Cuti'), ('libur', 'Libur')], default='hadir', max_length=20, verbose_name='Status')),
                ('persentase_kemiripan', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Persentase Kemiripan')),
                ('foto_masuk', models.ImageField(blank=True, null=True, upload_to='hr/absensi/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Masuk')),
                ('foto_keluar', models.ImageField(blank=True, null=True, upload_to='hr/absensi/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Keluar')),
                ('lokasi_masuk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi Masuk')),
                ('lokasi_keluar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi Keluar')),
                ('jarak_masuk', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Jarak Masuk (m)')),
                ('jarak_keluar', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Jarak Keluar (m)')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'ordering': ['-tanggal', 'karyawan'],
            },
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Departemen')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='FotoWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='hr/wajah/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Wajah')),
                ('encoding', models.TextField(blank=True, null=True, verbose_name='Face Encoding')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto Wajah',
                'verbose_name_plural': 'Foto Wajah',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Jabatan')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Jabatan')),
                ('level', models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive')], default='staff', max_length=20, verbose_name='Level')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Pokok')),
                ('tunjangan_jabatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Jabatan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Tugas')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Jabatan',
                'ordering': ['departemen', 'level', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True, verbose_name='NIK Karyawan')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hr/karyawan/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Karyawan')),
                ('tanggal_masuk', models.DateField(verbose_name='Tanggal Masuk')),
                ('tanggal_keluar', models.DateField(blank=True, null=True, verbose_name='Tanggal Keluar')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('cuti', 'Cuti'), ('resign', 'Resign'), ('phk', 'PHK')], default='aktif', max_length=20, verbose_name='Status')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Pokok')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PengaturanAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Pengaturan Default', max_length=100, verbose_name='Nama Pengaturan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif (Gunakan Pengaturan Ini)')),
                ('jam_masuk', models.TimeField(default='08:00:00', verbose_name='Jam Masuk')),
                ('jam_pulang', models.TimeField(default='17:00:00', verbose_name='Jam Pulang')),
                ('toleransi_terlambat', models.PositiveIntegerField(default=15, verbose_name='Toleransi Terlambat (menit)')),
                ('hari_kerja', models.CharField(default='0,1,2,3,4', help_text='Format: 0=Senin, 1=Selasa, dst. Contoh: 0,1,2,3,4 untuk Senin-Jumat', max_length=50, verbose_name='Hari Kerja')),
                ('zona_waktu', models.CharField(choices=[('Asia/Jakarta', 'WIB (Jakarta)'), ('Asia/Makassar', 'WITA (Makassar)'), ('Asia/Jayapura', 'WIT (Jayapura)')], default='Asia/Jakarta', max_length=50, verbose_name='Zona Waktu')),
                ('nama_lokasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Lokasi Kantor')),
                ('alamat_lokasi', models.TextField(blank=True, null=True, verbose_name='Alamat Kantor')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('radius_lokasi', models.PositiveIntegerField(default=100, help_text='Radius maksimal untuk absensi dari lokasi kantor', verbose_name='Radius Lokasi (meter)')),
                ('wajib_foto', models.BooleanField(default=True, verbose_name='Wajib Foto Saat Absen')),
                ('wajib_lokasi', models.BooleanField(default=False, verbose_name='Wajib Dalam Lokasi')),
                ('wajib_face_recognition', models.BooleanField(default=False, verbose_name='Wajib Face Recognition')),
                ('mulai_lembur_setelah', models.TimeField(default='18:00:00', help_text='Jam mulai dihitung lembur', verbose_name='Lembur Dimulai Setelah')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Absensi',
                'verbose_name_plural': 'Pengaturan Absensi',
                'ordering': ['-aktif', '-diupdate_pada'],
            },
        ),
        migrations.CreateModel(
            name='Penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_bulan', models.PositiveIntegerField(verbose_name='Bulan')),
                ('periode_tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Pokok')),
                ('tunjangan_jabatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Jabatan')),
                ('tunjangan_makan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Makan')),
                ('tunjangan_transport', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Transport')),
                ('tunjangan_lainnya', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Lainnya')),
                ('lembur', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Lembur')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bonus')),
                ('potongan_bpjs_kesehatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BPJS Kesehatan')),
                ('potongan_bpjs_ketenagakerjaan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BPJS Ketenagakerjaan')),
                ('potongan_pph21', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPh 21')),
                ('potongan_lainnya', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Potongan Lainnya')),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Pendapatan')),
                ('total_potongan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Potongan')),
                ('gaji_bersih', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Bersih')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diproses', 'Diproses'), ('dibayar', 'Dibayar'), ('batal', 'Batal')], default='draft', max_length=20, verbose_name='Status')),
                ('tanggal_bayar', models.DateField(blank=True, null=True, verbose_name='Tanggal Bayar')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penggajian',
                'verbose_name_plural': 'Penggajian',
                'ordering': ['-periode_tahun', '-periode_bulan', 'karyawan'],
            },
        ),
    ]
