# Generated by Django 5.0.6 on 2026-02-08 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Departemen')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Departemen')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Jabatan')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Jabatan')),
                ('level', models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Director'), ('executive', 'Executive')], default='staff', max_length=20, verbose_name='Level')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Pokok')),
                ('tunjangan_jabatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Jabatan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi Tugas')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jabatan_set', to='hr.departemen', verbose_name='Departemen')),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Jabatan',
                'ordering': ['departemen', 'level', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True, verbose_name='NIK Karyawan')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hr/karyawan/', verbose_name='Foto Karyawan')),
                ('tanggal_masuk', models.DateField(verbose_name='Tanggal Masuk')),
                ('tanggal_keluar', models.DateField(blank=True, null=True, verbose_name='Tanggal Keluar')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('cuti', 'Cuti'), ('resign', 'Resign'), ('phk', 'PHK')], default='aktif', max_length=20, verbose_name='Status')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Pokok')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karyawan_set', to='hr.departemen', verbose_name='Departemen')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan_dibuat', to=settings.AUTH_USER_MODEL)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karyawan_set', to='hr.jabatan', verbose_name='Jabatan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan', to=settings.AUTH_USER_MODEL, verbose_name='Akun User')),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='FotoWajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='hr/wajah/', verbose_name='Foto Wajah')),
                ('encoding', models.TextField(blank=True, null=True, verbose_name='Face Encoding')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_wajah_set', to='hr.karyawan', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Foto Wajah',
                'verbose_name_plural': 'Foto Wajah',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.AddField(
            model_name='departemen',
            name='kepala_departemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departemen_dipimpin', to='hr.karyawan', verbose_name='Kepala Departemen'),
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jam_masuk', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('jam_keluar', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('terlambat', 'Terlambat'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha'), ('cuti', 'Cuti'), ('libur', 'Libur')], default='hadir', max_length=20, verbose_name='Status')),
                ('foto_masuk', models.ImageField(blank=True, null=True, upload_to='hr/absensi/', verbose_name='Foto Masuk')),
                ('foto_keluar', models.ImageField(blank=True, null=True, upload_to='hr/absensi/', verbose_name='Foto Keluar')),
                ('lokasi_masuk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi Masuk')),
                ('lokasi_keluar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi Keluar')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_set', to='hr.karyawan', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Absensi',
                'verbose_name_plural': 'Absensi',
                'ordering': ['-tanggal', 'karyawan'],
                'unique_together': {('karyawan', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='Penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_bulan', models.PositiveIntegerField(verbose_name='Bulan')),
                ('periode_tahun', models.PositiveIntegerField(verbose_name='Tahun')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Pokok')),
                ('tunjangan_jabatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Jabatan')),
                ('tunjangan_makan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Makan')),
                ('tunjangan_transport', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Transport')),
                ('tunjangan_lainnya', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tunjangan Lainnya')),
                ('lembur', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Lembur')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bonus')),
                ('potongan_bpjs_kesehatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BPJS Kesehatan')),
                ('potongan_bpjs_ketenagakerjaan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BPJS Ketenagakerjaan')),
                ('potongan_pph21', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPh 21')),
                ('potongan_lainnya', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Potongan Lainnya')),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Pendapatan')),
                ('total_potongan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Potongan')),
                ('gaji_bersih', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gaji Bersih')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('diproses', 'Diproses'), ('dibayar', 'Dibayar'), ('batal', 'Batal')], default='draft', max_length=20, verbose_name='Status')),
                ('tanggal_bayar', models.DateField(blank=True, null=True, verbose_name='Tanggal Bayar')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggajian_dibuat', to=settings.AUTH_USER_MODEL)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggajian_set', to='hr.karyawan', verbose_name='Karyawan')),
            ],
            options={
                'verbose_name': 'Penggajian',
                'verbose_name_plural': 'Penggajian',
                'ordering': ['-periode_tahun', '-periode_bulan', 'karyawan'],
                'unique_together': {('karyawan', 'periode_bulan', 'periode_tahun')},
            },
        ),
    ]
