# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='jabatan',
            name='departemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jabatan_set', to='hr.departemen', verbose_name='Departemen'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_karyawan_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='departemen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karyawan_set', to='hr.departemen', verbose_name='Departemen'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='jabatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='karyawan_set', to='hr.jabatan', verbose_name='Jabatan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karyawan', to=settings.AUTH_USER_MODEL, verbose_name='Akun User'),
        ),
        migrations.AddField(
            model_name='fotowajah',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_wajah_set', to='hr.karyawan', verbose_name='Karyawan'),
        ),
        migrations.AddField(
            model_name='departemen',
            name='kepala_departemen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departemen_dipimpin', to='hr.karyawan', verbose_name='Kepala Departemen'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi_set', to='hr.karyawan', verbose_name='Karyawan'),
        ),
        migrations.AddField(
            model_name='pengaturanabsensi',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Kosongkan untuk pengaturan default (berlaku untuk karyawan tanpa cabang)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaturan_absensi_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='pengaturan_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_set', to='hr.pengaturanabsensi', verbose_name='Pengaturan yang Digunakan'),
        ),
        migrations.AddField(
            model_name='penggajian',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Otomatis dari cabang karyawan jika tidak diisi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggajian_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='penggajian',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggajian_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penggajian',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggajian_set', to='hr.karyawan', verbose_name='Karyawan'),
        ),
        migrations.AddField(
            model_name='penggajian',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, help_text='Metode pembayaran gaji (Kas/Transfer Bank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggajian_set', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['aktif', 'status'], name='hr_emp_aktif_status_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['departemen', 'aktif'], name='hr_emp_dept_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['jabatan', 'aktif'], name='hr_emp_jabatan_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['cabang', 'aktif'], name='hr_emp_cabang_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='absensi',
            index=models.Index(fields=['tanggal', 'status'], name='hr_abs_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='absensi',
            index=models.Index(fields=['cabang', 'tanggal'], name='hr_abs_cabang_tgl_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='absensi',
            unique_together={('karyawan', 'tanggal')},
        ),
        migrations.AddIndex(
            model_name='penggajian',
            index=models.Index(fields=['periode_tahun', 'periode_bulan', 'status'], name='hr_pay_period_status_idx'),
        ),
        migrations.AddIndex(
            model_name='penggajian',
            index=models.Index(fields=['status', 'tanggal_bayar'], name='hr_pay_status_tgl_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='penggajian',
            unique_together={('karyawan', 'periode_bulan', 'periode_tahun')},
        ),
    ]
