# Generated by Django 5.0.6 on 2026-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Pengaturan Default', max_length=100, verbose_name='Nama Pengaturan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif (Gunakan Pengaturan Ini)')),
                ('jam_masuk', models.TimeField(default='08:00:00', verbose_name='Jam Masuk')),
                ('jam_pulang', models.TimeField(default='17:00:00', verbose_name='Jam Pulang')),
                ('toleransi_terlambat', models.PositiveIntegerField(default=15, verbose_name='Toleransi Terlambat (menit)')),
                ('hari_kerja', models.CharField(default='0,1,2,3,4', help_text='Format: 0=Senin, 1=Selasa, dst. Contoh: 0,1,2,3,4 untuk Senin-Jumat', max_length=50, verbose_name='Hari Kerja')),
                ('zona_waktu', models.CharField(choices=[('Asia/Jakarta', 'WIB (Jakarta)'), ('Asia/Makassar', 'WITA (Makassar)'), ('Asia/Jayapura', 'WIT (Jayapura)')], default='Asia/Jakarta', max_length=50, verbose_name='Zona Waktu')),
                ('nama_lokasi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Lokasi Kantor')),
                ('alamat_lokasi', models.TextField(blank=True, null=True, verbose_name='Alamat Kantor')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('radius_lokasi', models.PositiveIntegerField(default=100, help_text='Radius maksimal untuk absensi dari lokasi kantor', verbose_name='Radius Lokasi (meter)')),
                ('wajib_foto', models.BooleanField(default=True, verbose_name='Wajib Foto Saat Absen')),
                ('wajib_lokasi', models.BooleanField(default=False, verbose_name='Wajib Dalam Lokasi')),
                ('wajib_face_recognition', models.BooleanField(default=False, verbose_name='Wajib Face Recognition')),
                ('mulai_lembur_setelah', models.TimeField(default='18:00:00', help_text='Jam mulai dihitung lembur', verbose_name='Lembur Dimulai Setelah')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Absensi',
                'verbose_name_plural': 'Pengaturan Absensi',
                'ordering': ['-aktif', '-diupdate_pada'],
            },
        ),
    ]
