# Generated by Django 5.0.6 on 2026-02-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_pengaturan_absensi'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='persentase_kemiripan',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Persentase Kemiripan'),
        ),
    ]
