# Generated by Django 6.0.3 on 2026-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_absensi_persentase_kemiripan'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='jarak_keluar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Jarak Keluar (m)'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='jarak_masuk',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Jarak Masuk (m)'),
        ),
    ]
