# Generated by Django 6.0.3 on 2026-05-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_absensi_jarak_masuk_keluar'),
        ('produk', '0006_produk_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensi',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='absensi',
            name='pengaturan_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi_set', to='hr.pengaturanabsensi', verbose_name='Pengaturan yang Digunakan'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_karyawan_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='pengaturanabsensi',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Kosongkan untuk pengaturan default (berlaku untuk karyawan tanpa cabang)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaturan_absensi_set', to='produk.gudang', verbose_name='Cabang'),
        ),
    ]
