# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_add_cabang_multicabang_support'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='absensi',
            index=models.Index(fields=['tanggal', 'status'], name='hr_abs_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='absensi',
            index=models.Index(fields=['cabang', 'tanggal'], name='hr_abs_cabang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['aktif', 'status'], name='hr_emp_aktif_status_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['departemen', 'aktif'], name='hr_emp_dept_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['jabatan', 'aktif'], name='hr_emp_jabatan_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='karyawan',
            index=models.Index(fields=['cabang', 'aktif'], name='hr_emp_cabang_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='penggajian',
            index=models.Index(fields=['periode_tahun', 'periode_bulan', 'status'], name='hr_pay_period_status_idx'),
        ),
        migrations.AddIndex(
            model_name='penggajian',
            index=models.Index(fields=['status', 'tanggal_bayar'], name='hr_pay_status_tgl_idx'),
        ),
    ]
