# Generated by Django 6.0.3 on 2026-05-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_performance_indexes'),
        ('pos', '0010_postransactionitem_hpp_snapshot'),
        ('produk', '0008_merge_0007_performance_indexes_0007_produk_kena_ppn'),
    ]

    operations = [
        migrations.AddField(
            model_name='penggajian',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Otomatis dari cabang karyawan jika tidak diisi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggajian_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='penggajian',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, help_text='Metode pembayaran gaji (Kas/Transfer Bank)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penggajian_set', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
    ]
