# Generated by Django 6.0.3 on 2026-05-22 09:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_penggajian_cabang_penggajian_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensi',
            name='foto_keluar',
            field=models.ImageField(blank=True, null=True, upload_to='hr/absensi/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Keluar'),
        ),
        migrations.AlterField(
            model_name='absensi',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, upload_to='hr/absensi/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Masuk'),
        ),
        migrations.AlterField(
            model_name='fotowajah',
            name='foto',
            field=models.ImageField(upload_to='hr/wajah/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Wajah'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='hr/karyawan/', validators=[apps.core.validators.validate_image_file], verbose_name='Foto Karyawan'),
        ),
    ]
