# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(default='ri-tools-line', help_text='Class icon Remix Icon', max_length=50, verbose_name='Icon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Service',
                'verbose_name_plural': 'Kategori Service',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Pelanggan')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Pelanggan')),
                ('telepon', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Perangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Jenis Perangkat')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(default='ri-smartphone-line', help_text='Class icon Remix Icon, contoh: ri-smartphone-line', max_length=50, verbose_name='Icon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jenis Perangkat',
                'verbose_name_plural': 'Jenis Perangkat',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='JenisService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Layanan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('foto', models.ImageField(blank=True, help_text='Foto/gambar untuk jenis layanan ini', null=True, upload_to='service_center/jenis/', verbose_name='Foto Layanan')),
                ('harga_standar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Standar (Rp)')),
                ('estimasi_waktu', models.CharField(blank=True, help_text='Contoh: 1-2 jam, 1 hari', max_length=50, null=True, verbose_name='Estimasi Waktu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jenis_services', to='service_center.kategoriservice', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Jenis Service',
                'verbose_name_plural': 'Jenis Service',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_service', models.CharField(max_length=50, unique=True, verbose_name='Nomor Service')),
                ('kode_unik', models.CharField(blank=True, help_text='Kode unik untuk cek status oleh pelanggan', max_length=8, unique=True, verbose_name='Kode Tracking')),
                ('tanggal_masuk', models.DateTimeField(verbose_name='Tanggal Masuk')),
                ('merek', models.CharField(max_length=100, verbose_name='Merek')),
                ('model_tipe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model / Tipe')),
                ('nomor_seri', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Seri / IMEI')),
                ('warna', models.CharField(blank=True, max_length=50, null=True, verbose_name='Warna')),
                ('keluhan', models.TextField(verbose_name='Keluhan Pelanggan')),
                ('kondisi_fisik', models.TextField(blank=True, help_text='Deskripsi kondisi fisik perangkat saat diterima (lecet, retak, dll)', null=True, verbose_name='Kondisi Fisik')),
                ('kelengkapan', models.TextField(blank=True, help_text='Barang yang disertakan (charger, dus, SIM card, dll)', null=True, verbose_name='Kelengkapan')),
                ('password_perangkat', models.CharField(blank=True, help_text='Password lock screen jika diperlukan untuk diagnosa', max_length=100, null=True, verbose_name='Password / PIN Perangkat')),
                ('gambar_perangkat', models.ImageField(blank=True, null=True, upload_to='service_center/perangkat/', verbose_name='Foto Perangkat')),
                ('status', models.CharField(choices=[('diterima', 'Diterima'), ('diagnosa', 'Diagnosa'), ('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('dikerjakan', 'Sedang Dikerjakan'), ('selesai', 'Selesai'), ('diambil', 'Sudah Diambil'), ('dibatalkan', 'Dibatalkan')], default='diterima', max_length=25, verbose_name='Status')),
                ('prioritas', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('express', 'Express')], default='normal', max_length=10, verbose_name='Prioritas')),
                ('estimasi_biaya', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimasi Biaya')),
                ('biaya_akhir', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya Akhir')),
                ('dp_bayar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='DP / Uang Muka')),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPN / Pajak (Rp)')),
                ('status_bayar', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('dp', 'DP (Uang Muka)'), ('lunas', 'Lunas')], default='belum_bayar', max_length=15, verbose_name='Status Pembayaran')),
                ('estimasi_selesai', models.DateField(blank=True, null=True, verbose_name='Estimasi Selesai')),
                ('catatan_teknisi', models.TextField(blank=True, null=True, verbose_name='Catatan Teknisi')),
                ('catatan_internal', models.TextField(blank=True, help_text='Catatan internal yang tidak ditampilkan ke pelanggan', null=True, verbose_name='Catatan Internal')),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('tanggal_diambil', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Diambil')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('cabang', models.ForeignKey(blank=True, help_text='Cabang/gudang tempat order service ini ditangani', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services', to='produk.gudang', verbose_name='Cabang / Gudang')),
                ('diterima_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_service_diterima', to=settings.AUTH_USER_MODEL, verbose_name='Diterima Oleh')),
                ('metode_pembayaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services', to='pos.metodepembayaran', verbose_name='Metode Pembayaran')),
                ('teknisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_service_teknisi', to=settings.AUTH_USER_MODEL, verbose_name='Teknisi')),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_services', to='service_center.pelanggan', verbose_name='Pelanggan')),
                ('jenis_perangkat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_services', to='service_center.perangkat', verbose_name='Jenis Perangkat')),
            ],
            options={
                'verbose_name': 'Order Service',
                'verbose_name_plural': 'Order Service',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=200, verbose_name='Nama Layanan / Perbaikan')),
                ('biaya', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('jenis_service', models.ForeignKey(blank=True, help_text='Pilih dari daftar layanan standar, atau isi manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_services', to='service_center.jenisservice', verbose_name='Jenis Service')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_center.orderservice', verbose_name='Order Service')),
            ],
            options={
                'verbose_name': 'Item Service',
                'verbose_name_plural': 'Item Service',
            },
        ),
        migrations.CreateModel(
            name='RiwayatStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sebelum', models.CharField(max_length=25, verbose_name='Status Sebelum')),
                ('status_sesudah', models.CharField(max_length=25, verbose_name='Status Sesudah')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_status', to='service_center.orderservice', verbose_name='Order Service')),
            ],
            options={
                'verbose_name': 'Riwayat Status',
                'verbose_name_plural': 'Riwayat Status',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PenggunaanSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Satuan')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('stok_dikurangi', models.BooleanField(default=False, help_text='Flag apakah stok sudah dikurangi saat save', verbose_name='Stok Sudah Dikurangi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggunaan_service', to='produk.gudang', verbose_name='Gudang Sumber')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggunaan_sparepart', to='service_center.orderservice', verbose_name='Order Service')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggunaan_service', to='produk.produk', verbose_name='Sparepart')),
            ],
            options={
                'verbose_name': 'Penggunaan Sparepart',
                'verbose_name_plural': 'Penggunaan Sparepart',
                'ordering': ['-dibuat_pada'],
                'indexes': [models.Index(fields=['produk', 'gudang'], name='svc_sp_prod_gdg_idx'), models.Index(fields=['order_service', 'produk'], name='svc_sp_order_prod_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['status', 'tanggal_masuk'], name='svc_order_status_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['status_bayar', 'tanggal_masuk'], name='svc_order_bayar_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['cabang', 'tanggal_masuk'], name='svc_order_cabang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['teknisi', 'status'], name='svc_order_teknisi_st_idx'),
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['pelanggan', 'tanggal_masuk'], name='svc_order_plg_tgl_idx'),
        ),
    ]
