# Generated by Django 6.0.3 on 2026-06-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_metodepembayaran_gambar'),
        ('produk', '0010_produk_tipe'),
        ('service_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Cabang/gudang tempat order service ini ditangani', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services_cabang', to='produk.gudang', verbose_name='Cabang / Gudang'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='jenis_perangkat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_services_perangkat', to='service_center.perangkat', verbose_name='Jenis Perangkat'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services_pembayaran', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='pelanggan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_services_pelanggan', to='service_center.pelanggan', verbose_name='Pelanggan'),
        ),
        migrations.AlterField(
            model_name='penggunaansparepart',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggunaan_sparepart', to='produk.gudang', verbose_name='Gudang Sumber'),
        ),
        migrations.AlterField(
            model_name='penggunaansparepart',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggunaan_sparepart', to='produk.produk', verbose_name='Sparepart'),
        ),
    ]
