# Generated by Django 5.0.6 on 2026-03-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Layanan')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('harga_standar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Standar (Rp)')),
                ('estimasi_waktu', models.CharField(blank=True, help_text='Contoh: 1-2 jam, 1 hari', max_length=50, null=True, verbose_name='Estimasi Waktu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Service',
                'verbose_name_plural': 'Jenis Service',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='KategoriService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(default='ri-tools-line', help_text='Class icon Remix Icon', max_length=50, verbose_name='Icon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori Service',
                'verbose_name_plural': 'Kategori Service',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='orderservice',
            name='kode_unik',
            field=models.CharField(blank=True, help_text='Kode unik untuk cek status oleh pelanggan', max_length=8, unique=True, verbose_name='Kode Tracking'),
        ),
        migrations.AddField(
            model_name='itemservice',
            name='jenis_service',
            field=models.ForeignKey(blank=True, help_text='Pilih dari daftar layanan standar, atau isi manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_services', to='service_center.jenisservice', verbose_name='Jenis Service'),
        ),
        migrations.AddField(
            model_name='jenisservice',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jenis_services', to='service_center.kategoriservice', verbose_name='Kategori'),
        ),
    ]
