# Generated by Django 5.0.6 on 2026-03-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0002_jenisservice_kategoriservice_orderservice_kode_unik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenisservice',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto/gambar untuk jenis layanan ini', null=True, upload_to='service_center/jenis/', verbose_name='Foto Layanan'),
        ),
    ]
