# Generated by Django 5.0.6 on 2026-03-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_konversisatuan'),
        ('service_center', '0003_add_foto_to_jenisservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenggunaanSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga Satuan')),
                ('catatan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Catatan')),
                ('stok_dikurangi', models.BooleanField(default=False, help_text='Flag apakah stok sudah dikurangi saat save', verbose_name='Stok Sudah Dikurangi')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggunaan_service', to='produk.gudang', verbose_name='Gudang Sumber')),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penggunaan_sparepart', to='service_center.orderservice', verbose_name='Order Service')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penggunaan_service', to='produk.produk', verbose_name='Sparepart')),
            ],
            options={
                'verbose_name': 'Penggunaan Sparepart',
                'verbose_name_plural': 'Penggunaan Sparepart',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
