# Generated by Django 6.0.3 on 2026-04-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_add_customer_fk'),
        ('service_center', '0004_add_penggunaan_sparepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
    ]
