# Generated by Django 6.0.3 on 2026-04-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_produk_metode_pembayaran'),
        ('service_center', '0005_orderservice_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Cabang/gudang tempat order service ini ditangani', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_services', to='produk.gudang', verbose_name='Cabang / Gudang'),
        ),
    ]
