# Generated by Django 5.0.6 on 2026-06-02 01:08

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiBiaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(max_length=50, unique=True, verbose_name='Nomor Transaksi')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('bukti', models.FileField(blank=True, null=True, upload_to='biaya/', validators=[apps.core.validators.validate_expense_proof], verbose_name='Bukti (Foto/PDF)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Pembatalan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaksi Biaya',
                'verbose_name_plural': 'Transaksi Biaya',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='KategoriBiaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('akun_beban', models.ForeignKey(blank=True, help_text='Akun CoA spesifik untuk kategori ini. Kosong = fallback ke 6-9000', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategori_biaya', to='akuntansi.akun', verbose_name='Akun Beban (CoA)')),
            ],
            options={
                'verbose_name': 'Kategori Biaya',
                'verbose_name_plural': 'Kategori Biaya',
                'ordering': ['nama'],
            },
        ),
    ]
