# Generated by Django 5.0.6 on 2026-01-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBiaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori Biaya',
                'verbose_name_plural': 'Kategori Biaya',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiBiaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(max_length=50, unique=True, verbose_name='Nomor Transaksi')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('bukti', models.FileField(blank=True, null=True, upload_to='biaya/', verbose_name='Bukti (Foto/PDF)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='draft', max_length=20, verbose_name='Status')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biaya_dibuat', to=settings.AUTH_USER_MODEL)),
                ('disetujui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biaya_disetujui', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='biaya.kategoribiaya', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Transaksi Biaya',
                'verbose_name_plural': 'Transaksi Biaya',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
