# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biaya', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksibiaya',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_biaya', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biaya_dibatalkan', to=settings.AUTH_USER_MODEL, verbose_name='Dibatalkan Oleh'),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biaya_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='disetujui_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biaya_disetujui', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='biaya.kategoribiaya', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_biaya', to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddIndex(
            model_name='kategoribiaya',
            index=models.Index(fields=['aktif', 'nama'], name='biaya_kat_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['tanggal', 'status'], name='biaya_trx_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['kategori', 'status'], name='biaya_trx_kat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['cabang', 'tanggal'], name='biaya_trx_cbg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='biaya_trx_pay_status_idx'),
        ),
    ]
