# Generated by Django 5.0.6 on 2026-02-22 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaya', '0002_add_metode_pembayaran'),
        ('produk', '0003_add_pajak_to_gudang'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksibiaya',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi_biaya', to='produk.gudang', verbose_name='Cabang'),
        ),
    ]
