# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaya', '0003_transaksibiaya_cabang'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kategoribiaya',
            index=models.Index(fields=['aktif', 'nama'], name='biaya_kat_aktif_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['tanggal', 'status'], name='biaya_trx_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['kategori', 'status'], name='biaya_trx_kat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['cabang', 'tanggal'], name='biaya_trx_cbg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksibiaya',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='biaya_trx_pay_status_idx'),
        ),
    ]
