# Generated by Django 6.0.3 on 2026-05-21 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0005_add_is_reversed_to_jurnalentry'),
        ('biaya', '0004_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoribiaya',
            name='akun_beban',
            field=models.ForeignKey(blank=True, help_text='Akun CoA spesifik untuk kategori ini. Kosong = fallback ke 6-9000', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kategori_biaya', to='akuntansi.akun', verbose_name='Akun Beban (CoA)'),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Pembatalan'),
        ),
        migrations.AddField(
            model_name='transaksibiaya',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biaya_dibatalkan', to=settings.AUTH_USER_MODEL, verbose_name='Dibatalkan Oleh'),
        ),
        migrations.AlterField(
            model_name='transaksibiaya',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
