# Generated by Django 6.0.3 on 2026-05-22 09:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biaya', '0006_backfill_kategori_akun_beban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksibiaya',
            name='bukti',
            field=models.FileField(blank=True, null=True, upload_to='biaya/', validators=[apps.core.validators.validate_expense_proof], verbose_name='Bukti (Foto/PDF)'),
        ),
    ]
