# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Nomor Jurnal')),
                ('tanggal', models.DateField(db_index=True, verbose_name='Tanggal')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('sumber', models.CharField(choices=[('manual', 'Manual'), ('pos', 'POS / Kasir'), ('so', 'Sales Order'), ('po', 'Purchase Order'), ('biaya', 'Biaya Operasional'), ('payroll', 'Penggajian'), ('adjustment', 'Adjustment Stok'), ('service', 'Service Center'), ('aset', 'Aset Tetap'), ('pajak', 'Perpajakan'), ('piutang', 'Pembayaran Piutang'), ('hutang', 'Pembayaran Hutang'), ('kas_bank', 'Kas & Bank / Treasury'), ('rekon', 'Rekonsiliasi Kas'), ('closing', 'Closing Entry / Tutup Buku'), ('pembalik', 'Jurnal Pembalik')], default='manual', max_length=20, verbose_name='Sumber')),
                ('sumber_id', models.IntegerField(blank=True, help_text='Primary key dari objek sumber (POS, SO, PO, dll)', null=True, verbose_name='ID Sumber')),
                ('sumber_ref', models.CharField(blank=True, help_text='Nomor transaksi sumber (contoh: POS/2026/05/09/0001)', max_length=50, verbose_name='Ref. Sumber')),
                ('is_posted', models.BooleanField(default=False, help_text='Jurnal yang sudah diposting tidak dapat dihapus', verbose_name='Sudah Diposting')),
                ('is_reversed', models.BooleanField(default=False, help_text='True jika jurnal ini sudah memiliki jurnal pembalik/reversal', verbose_name='Sudah Di-reverse')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jurnal Entry',
                'verbose_name_plural': 'Jurnal Entry',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='JurnalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debit')),
                ('kredit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kredit')),
                ('keterangan', models.CharField(blank=True, max_length=200, verbose_name='Keterangan')),
            ],
            options={
                'verbose_name': 'Jurnal Line',
                'verbose_name_plural': 'Jurnal Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeAkuntansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Periode')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_akhir', models.DateField(verbose_name='Tanggal Akhir')),
                ('is_aktif', models.BooleanField(default=False, verbose_name='Periode Aktif')),
                ('is_tutup', models.BooleanField(default=False, help_text='Periode yang sudah ditutup tidak dapat menerima jurnal baru', verbose_name='Sudah Ditutup')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Periode Akuntansi',
                'verbose_name_plural': 'Periode Akuntansi',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(db_index=True, help_text='Format: 1-1000 (Aset), 2-1000 (Kewajiban), dll', max_length=20, unique=True, verbose_name='Kode Akun')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Akun')),
                ('tipe', models.CharField(choices=[('aset', 'Aset (Aktiva)'), ('kewajiban', 'Kewajiban (Liabilitas)'), ('modal', 'Modal (Ekuitas)'), ('pendapatan', 'Pendapatan'), ('hpp', 'Harga Pokok Penjualan'), ('beban', 'Beban Operasional')], max_length=20, verbose_name='Tipe Akun')),
                ('sub_tipe', models.CharField(blank=True, choices=[('aset_lancar', 'Aset Lancar'), ('aset_tetap', 'Aset Tetap'), ('contra_aset', 'Contra Aset'), ('kewajiban_lancar', 'Kewajiban Lancar'), ('kewajiban_panjang', 'Kewajiban Jangka Panjang'), ('modal_pemilik', 'Modal Pemilik'), ('laba_ditahan', 'Laba Ditahan'), ('ikhtisar', 'Ikhtisar Laba/Rugi'), ('prive', 'Prive'), ('pendapatan_utama', 'Pendapatan Utama'), ('contra_pendapatan', 'Contra Pendapatan'), ('pendapatan_lain', 'Pendapatan Lainnya'), ('hpp_utama', 'HPP Utama'), ('beban_operasional', 'Beban Operasional')], max_length=30, verbose_name='Sub Tipe')),
                ('saldo_normal', models.CharField(choices=[('debit', 'Debit'), ('kredit', 'Kredit')], max_length=10, verbose_name='Saldo Normal')),
                ('deskripsi', models.TextField(blank=True, help_text='Penjelasan tentang akun ini', verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_system', models.BooleanField(default=False, help_text='Akun sistem tidak dapat dihapus', verbose_name='Akun Sistem')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='akuntansi.akun', verbose_name='Akun Induk')),
            ],
            options={
                'verbose_name': 'Akun (CoA)',
                'verbose_name_plural': 'Akun (CoA)',
                'ordering': ['kode'],
            },
        ),
    ]
