# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalentry',
            name='cabang',
            field=models.ForeignKey(blank=True, help_text='Cabang yang terkait dengan jurnal ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='jurnalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_entries', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='jurnalentry',
            name='jurnal_asal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_pembalik', to='akuntansi.jurnalentry', verbose_name='Jurnal Asal (jika pembalik)'),
        ),
        migrations.AddField(
            model_name='jurnalline',
            name='akun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurnal_lines', to='akuntansi.akun', verbose_name='Akun'),
        ),
        migrations.AddField(
            model_name='jurnalline',
            name='jurnal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='akuntansi.jurnalentry', verbose_name='Jurnal'),
        ),
        migrations.AddIndex(
            model_name='periodeakuntansi',
            index=models.Index(fields=['is_aktif', 'is_tutup'], name='akt_periode_status_idx'),
        ),
        migrations.AddField(
            model_name='jurnalentry',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.periodeakuntansi', verbose_name='Periode'),
        ),
        migrations.AddIndex(
            model_name='akun',
            index=models.Index(fields=['tipe', 'is_active'], name='akt_akun_tipe_active_idx'),
        ),
        migrations.AddIndex(
            model_name='akun',
            index=models.Index(fields=['sub_tipe', 'is_active'], name='akt_akun_sub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalline',
            index=models.Index(fields=['akun', 'jurnal'], name='akt_line_akun_jrn_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalentry',
            index=models.Index(fields=['tanggal', 'is_posted'], name='akt_jrn_tgl_post_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalentry',
            index=models.Index(fields=['sumber', 'sumber_id'], name='akt_jrn_src_id_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalentry',
            index=models.Index(fields=['cabang', 'tanggal'], name='akt_jrn_cbg_tgl_idx'),
        ),
    ]
