# Generated by Django 5.0.6 on 2026-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalentry',
            name='sumber',
            field=models.CharField(choices=[('manual', 'Manual'), ('pos', 'POS / Kasir'), ('so', 'Sales Order'), ('po', 'Purchase Order'), ('biaya', 'Biaya Operasional'), ('payroll', 'Penggajian'), ('adjustment', 'Adjustment Stok'), ('service', 'Service Center'), ('aset', 'Aset Tetap'), ('pajak', 'Perpajakan'), ('piutang', 'Pembayaran Piutang'), ('hutang', 'Pembayaran Hutang'), ('kas_bank', 'Kas & Bank / Treasury'), ('rekon', 'Rekonsiliasi Kas'), ('pembalik', 'Jurnal Pembalik')], default='manual', max_length=20, verbose_name='Sumber'),
        ),
    ]
