# Generated by Django 6.0.3 on 2026-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0002_add_kas_bank_journal_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='sub_tipe',
            field=models.CharField(blank=True, choices=[('aset_lancar', 'Aset Lancar'), ('aset_tetap', 'Aset Tetap'), ('contra_aset', 'Contra Aset'), ('kewajiban_lancar', 'Kewajiban Lancar'), ('kewajiban_panjang', 'Kewajiban Jangka Panjang'), ('modal_pemilik', 'Modal Pemilik'), ('laba_ditahan', 'Laba Ditahan'), ('ikhtisar', 'Ikhtisar Laba/Rugi'), ('prive', 'Prive'), ('pendapatan_utama', 'Pendapatan Utama'), ('contra_pendapatan', 'Contra Pendapatan'), ('pendapatan_lain', 'Pendapatan Lainnya'), ('hpp_utama', 'HPP Utama'), ('beban_operasional', 'Beban Operasional')], max_length=30, verbose_name='Sub Tipe'),
        ),
        migrations.AlterField(
            model_name='jurnalentry',
            name='sumber',
            field=models.CharField(choices=[('manual', 'Manual'), ('pos', 'POS / Kasir'), ('so', 'Sales Order'), ('po', 'Purchase Order'), ('biaya', 'Biaya Operasional'), ('payroll', 'Penggajian'), ('adjustment', 'Adjustment Stok'), ('service', 'Service Center'), ('aset', 'Aset Tetap'), ('pajak', 'Perpajakan'), ('piutang', 'Pembayaran Piutang'), ('hutang', 'Pembayaran Hutang'), ('kas_bank', 'Kas & Bank / Treasury'), ('rekon', 'Rekonsiliasi Kas'), ('closing', 'Closing Entry / Tutup Buku'), ('pembalik', 'Jurnal Pembalik')], default='manual', max_length=20, verbose_name='Sumber'),
        ),
    ]
