# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0003_alter_akun_sub_tipe_alter_jurnalentry_sumber'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='akun',
            index=models.Index(fields=['tipe', 'is_active'], name='akt_akun_tipe_active_idx'),
        ),
        migrations.AddIndex(
            model_name='akun',
            index=models.Index(fields=['sub_tipe', 'is_active'], name='akt_akun_sub_active_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalentry',
            index=models.Index(fields=['tanggal', 'is_posted'], name='akt_jrn_tgl_post_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalentry',
            index=models.Index(fields=['sumber', 'sumber_id'], name='akt_jrn_src_id_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalentry',
            index=models.Index(fields=['cabang', 'tanggal'], name='akt_jrn_cbg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='jurnalline',
            index=models.Index(fields=['akun', 'jurnal'], name='akt_line_akun_jrn_idx'),
        ),
        migrations.AddIndex(
            model_name='periodeakuntansi',
            index=models.Index(fields=['is_aktif', 'is_tutup'], name='akt_periode_status_idx'),
        ),
    ]
