# Generated by Django 6.0.3 on 2026-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnalentry',
            name='is_reversed',
            field=models.BooleanField(default=False, help_text='True jika jurnal ini sudah memiliki jurnal pembalik/reversal', verbose_name='Sudah Di-reverse'),
        ),
    ]
