# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(editable=False, max_length=50, unique=True, verbose_name='No. Hutang')),
                ('sumber', models.CharField(choices=[('po', 'Purchase Order'), ('manual', 'Input Manual')], default='manual', max_length=10, verbose_name='Sumber')),
                ('sumber_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='No. Referensi Sumber')),
                ('jumlah_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Total')),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Dibayar')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Hutang')),
                ('jatuh_tempo', models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo')),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('sebagian', 'Bayar Sebagian'), ('lunas', 'Lunas'), ('macet', 'Macet')], default='belum_bayar', max_length=15, verbose_name='Status')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hutang',
                'verbose_name_plural': 'Hutang',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PembayaranHutang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal Bayar')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah Bayar')),
                ('keterangan', models.TextField(blank=True, default='', verbose_name='Keterangan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pembayaran Hutang',
                'verbose_name_plural': 'Pembayaran Hutang',
                'ordering': ['-tanggal', '-dibuat_pada'],
            },
        ),
    ]
