# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akuntansi', '0002_initial'),
        ('hutang', '0001_initial'),
        ('pembelian', '0001_initial'),
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hutang',
            name='cabang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hutang_set', to='produk.gudang', verbose_name='Cabang'),
        ),
        migrations.AddField(
            model_name='hutang',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='hutang',
            name='jurnal_pembayaran',
            field=models.ForeignKey(blank=True, help_text='Jurnal otomatis saat hutang dibayar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_hutang', to='akuntansi.jurnalentry', verbose_name='Jurnal Pembayaran'),
        ),
        migrations.AddField(
            model_name='hutang',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hutang_set', to='pembelian.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='hutang',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hutang_set', to='pembelian.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='pembayaranhutang',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dicatat Oleh'),
        ),
        migrations.AddField(
            model_name='pembayaranhutang',
            name='hutang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran_set', to='hutang.hutang', verbose_name='Hutang'),
        ),
        migrations.AddField(
            model_name='pembayaranhutang',
            name='jurnal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntansi.jurnalentry', verbose_name='Jurnal Entry'),
        ),
        migrations.AddField(
            model_name='pembayaranhutang',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['tanggal', 'status'], name='ap_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['jatuh_tempo', 'status'], name='ap_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['supplier', 'status'], name='ap_sup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['cabang', 'status'], name='ap_cabang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['sumber', 'sumber_ref'], name='ap_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranhutang',
            index=models.Index(fields=['tanggal'], name='ap_pay_tanggal_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranhutang',
            index=models.Index(fields=['hutang', 'tanggal'], name='ap_pay_hutang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranhutang',
            index=models.Index(fields=['metode_pembayaran', 'tanggal'], name='ap_pay_metode_tgl_idx'),
        ),
    ]
