# Generated by Django 6.0.3 on 2026-05-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0001_initial'),
        ('hutang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hutang',
            name='jurnal_pembayaran',
            field=models.ForeignKey(blank=True, help_text='Jurnal otomatis saat hutang dibayar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_hutang', to='akuntansi.jurnalentry', verbose_name='Jurnal Pembayaran'),
        ),
    ]
