# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
        ('hutang', '0002_hutang_jurnal_pembayaran'),
        ('pembelian', '0004_purchaseorderitem_jumlah_konversi_and_more'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['tanggal', 'status'], name='ap_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['jatuh_tempo', 'status'], name='ap_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['supplier', 'status'], name='ap_sup_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['cabang', 'status'], name='ap_cabang_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hutang',
            index=models.Index(fields=['sumber', 'sumber_ref'], name='ap_source_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranhutang',
            index=models.Index(fields=['tanggal'], name='ap_pay_tanggal_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranhutang',
            index=models.Index(fields=['hutang', 'tanggal'], name='ap_pay_hutang_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaranhutang',
            index=models.Index(fields=['metode_pembayaran', 'tanggal'], name='ap_pay_metode_tgl_idx'),
        ),
    ]
