# Generated by Django 6.0.3 on 2026-03-18 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_log', '0002_enhance_activity_log'),
        ('produk', '0005_konversisatuan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField(verbose_name='Mulai Shift')),
                ('shift_end', models.DateTimeField(blank=True, null=True, verbose_name='Akhir Shift')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=0, help_text='Nominal uang yang seharusnya ada berdasarkan transaksi POS.', max_digits=15, verbose_name='Uang Seharusnya (Sistem)')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, help_text='Nominal uang fisik yang dilaporkan kasir saat tutup shift.', max_digits=15, verbose_name='Uang Fisik (Input Kasir)')),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0, help_text='Selisih antara uang fisik dan uang sistem. Positif = lebih, Negatif = kurang.', max_digits=15, verbose_name='Selisih (Rp)')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('status', models.CharField(choices=[('open', 'Shift Berjalan'), ('closed', 'Shift Ditutup'), ('reviewed', 'Sudah Direview')], default='open', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gudang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.gudang', verbose_name='Cabang/Gudang')),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Kasir')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Direview Oleh')),
            ],
            options={
                'verbose_name': 'Rekonsiliasi Kas',
                'verbose_name_plural': 'Rekonsiliasi Kas',
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('hapus_lunas', 'Hapus Data Lunas'), ('diskon_besar', 'Diskon Berlebihan'), ('po_markup', 'PO Mark-Up Harga'), ('stok_minus', 'Stok Minus'), ('diluar_jam', 'Aktivitas Diluar Jam'), ('adjustment_besar', 'Adjustment Stok Besar'), ('void_transaksi', 'Void Transaksi'), ('lainnya', 'Lainnya')], max_length=30, verbose_name='Jenis Anomali')),
                ('severity', models.CharField(choices=[('low', 'Rendah'), ('medium', 'Sedang'), ('high', 'Tinggi'), ('critical', 'Kritis')], default='medium', max_length=10, verbose_name='Tingkat Keparahan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('investigated', 'Sedang Diinvestigasi'), ('cleared', 'Aman / Wajar'), ('rejected', 'Terbukti Fraud')], default='pending', max_length=20, verbose_name='Status')),
                ('deskripsi', models.TextField(help_text='Penjelasan detail anomali yang terdeteksi.', verbose_name='Deskripsi Anomali')),
                ('nominal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nominal Terkait (Rp)')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model/Modul')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Objek')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Data JSON sebelum/sesudah perubahan.', verbose_name='Snapshot Data')),
                ('catatan_owner', models.TextField(blank=True, null=True, verbose_name='Catatan Owner/SPV')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Terdeteksi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='activity_log.useractivity', verbose_name='Log Aktivitas Terkait')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Direview Oleh')),
                ('user_terkait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_terkait', to=settings.AUTH_USER_MODEL, verbose_name='User Terkait')),
            ],
            options={
                'verbose_name': 'Fraud Alert',
                'verbose_name_plural': 'Fraud Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_delete_paid', models.BooleanField(default=False, help_text='Jika aktif, transaksi SO/PO/POS berstatus lunas tidak bisa dihapus.', verbose_name='Blokir Hapus Data Lunas')),
                ('block_negative_stock', models.BooleanField(default=False, help_text='Jika aktif, transaksi POS ditolak jika stok tidak mencukupi.', verbose_name='Blokir Stok Minus')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=100.0, help_text='Persentase maksimal diskon yang boleh diberikan kasir. Default 100% (tanpa batas).', max_digits=5, verbose_name='Batas Maksimal Diskon (%)')),
                ('jam_operasional_mulai', models.TimeField(default='07:00', help_text='Waktu mulai jam operasional toko.', verbose_name='Jam Operasional Mulai')),
                ('jam_operasional_selesai', models.TimeField(default='22:00', help_text='Waktu selesai jam operasional toko.', verbose_name='Jam Operasional Selesai')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh')),
            ],
            options={
                'verbose_name': 'Pengaturan Fraud',
                'verbose_name_plural': 'Pengaturan Fraud',
            },
        ),
    ]
