# Generated by Django 6.0.3 on 2026-04-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='jenis',
            field=models.CharField(choices=[('hapus_lunas', 'Hapus Data Lunas'), ('diskon_besar', 'Diskon Berlebihan'), ('po_markup', 'PO Mark-Up Harga'), ('stok_minus', 'Stok Minus'), ('diluar_jam', 'Aktivitas Diluar Jam'), ('adjustment_besar', 'Adjustment Stok Besar'), ('void_transaksi', 'Void Transaksi'), ('anomali_lainnya', 'Anomali Lainnya'), ('lainnya', 'Lainnya')], max_length=30, verbose_name='Jenis Anomali'),
        ),
    ]
