# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_log', '0001_initial'),
        ('fraud_detection', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreconciliation',
            name='gudang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.gudang', verbose_name='Cabang/Gudang'),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='kasir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Kasir'),
        ),
        migrations.AddField(
            model_name='cashreconciliation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Direview Oleh'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts', to='activity_log.useractivity', verbose_name='Log Aktivitas Terkait'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Direview Oleh'),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='user_terkait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_alerts_terkait', to=settings.AUTH_USER_MODEL, verbose_name='User Terkait'),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diubah Oleh'),
        ),
    ]
