# Generated by Django 6.0.3 on 2026-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudrule',
            name='max_sparepart_qty',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Batas maksimal jumlah sparepart per item service. Default 10.', max_digits=10, verbose_name='Batas Maksimal Qty Sparepart'),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='max_transaction_amount',
            field=models.DecimalField(decimal_places=2, default=10000000.0, help_text='Jika nilai transaksi melebihi batas ini, buat FraudAlert. Default Rp 10.000.000.', max_digits=15, verbose_name='Batas Transaksi Mencurigakan (Rp)'),
        ),
        migrations.AddField(
            model_name='fraudrule',
            name='min_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Jika margin keuntungan di bawah % ini, buat FraudAlert. Default 0% (tanpa alert).', max_digits=5, verbose_name='Margin Minimal (%)'),
        ),
    ]
