# Generated by Django 6.0.3 on 2026-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_alter_fraudalert_jenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudrule',
            name='max_sparepart_qty',
            field=models.PositiveIntegerField(default=10, help_text='Jumlah maksimal sparepart per item yang dianggap wajar. Lebih dari ini akan memicu alert fraud.', verbose_name='Batas Jumlah Sparepart per Item'),
        ),
    ]
