# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI ChatGPT'), ('groq', 'Groq (Gratis)')], default='groq', max_length=20, verbose_name='Provider AI')),
                ('api_key', models.CharField(blank=True, default='', help_text='API Key dari Google AI Studio, OpenAI Platform, atau Groq Console', max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(default='llama-3.3-70b-versatile', help_text='Contoh: gemini-2.0-flash, gpt-4o-mini, llama-3.3-70b-versatile', max_length=100, verbose_name='Model AI')),
                ('aktif', models.BooleanField(default=True, help_text='Aktifkan/nonaktifkan fitur AI Chat', verbose_name='Status Aktif')),
                ('ai_name', models.CharField(default='AI Assistant', help_text='Nama yang ditampilkan di header chat AI', max_length=100, verbose_name='Nama AI')),
                ('max_tokens', models.IntegerField(default=1024, help_text='Batas maksimal token respons AI', verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='Kreativitas AI (0.0 = fokus, 1.0 = kreatif)', verbose_name='Temperature')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Instruksi tambahan untuk AI (opsional)', verbose_name='System Prompt Tambahan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan AI Assistant',
                'verbose_name_plural': 'Pengaturan AI Assistant',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant')], max_length=10, verbose_name='Role')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('intent', models.CharField(blank=True, default='', max_length=50, verbose_name='Intent Terdeteksi')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='Sumber AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Riwayat Chat',
                'verbose_name_plural': 'Riwayat Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('up', '👍 Bagus'), ('down', '👎 Kurang')], max_length=4, verbose_name='Feedback')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Teks Pesan AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_feedback', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assistant.chathistory', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Feedback Chat',
                'verbose_name_plural': 'Feedback Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_e58337_idx'),
        ),
    ]
