# Generated by Django 5.0.6 on 2026-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI ChatGPT')], default='gemini', max_length=20, verbose_name='Provider AI')),
                ('api_key', models.CharField(blank=True, default='', help_text='API Key dari Google AI Studio atau OpenAI Platform', max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(default='gemini-2.0-flash', help_text='Contoh: gemini-2.0-flash, gpt-3.5-turbo, gpt-4o-mini', max_length=100, verbose_name='Model AI')),
                ('aktif', models.BooleanField(default=True, help_text='Aktifkan/nonaktifkan fitur AI Chat', verbose_name='Status Aktif')),
                ('max_tokens', models.IntegerField(default=1024, help_text='Batas maksimal token respons AI', verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='Kreativitas AI (0.0 = fokus, 1.0 = kreatif)', verbose_name='Temperature')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Instruksi tambahan untuk AI (opsional)', verbose_name='System Prompt Tambahan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan AI Assistant',
                'verbose_name_plural': 'Pengaturan AI Assistant',
            },
        ),
    ]
