# Generated by Django 5.0.6 on 2026-02-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='API Key dari Google AI Studio, OpenAI Platform, atau Groq Console', max_length=500, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='model_name',
            field=models.CharField(default='llama-3.3-70b-versatile', help_text='Contoh: gemini-2.0-flash, gpt-4o-mini, llama-3.3-70b-versatile', max_length=100, verbose_name='Model AI'),
        ),
        migrations.AlterField(
            model_name='aiassistantconfig',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI ChatGPT'), ('groq', 'Groq (Gratis)')], default='groq', max_length=20, verbose_name='Provider AI'),
        ),
    ]
