# Generated by Django 5.0.6 on 2026-03-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_alter_aiassistantconfig_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant')], max_length=10, verbose_name='Role')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('intent', models.CharField(blank=True, default='', max_length=50, verbose_name='Intent Terdeteksi')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='Sumber AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_history', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Riwayat Chat',
                'verbose_name_plural': 'Riwayat Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('up', '👍 Bagus'), ('down', '👎 Kurang')], max_length=4, verbose_name='Feedback')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Teks Pesan AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_feedback', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assistant.chathistory', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Feedback Chat',
                'verbose_name_plural': 'Feedback Chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_e58337_idx'),
        ),
    ]
