# Generated by Django 5.0.6 on 2026-03-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_chathistory_chatfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantconfig',
            name='ai_name',
            field=models.CharField(default='AI Assistant', help_text='Nama yang ditampilkan di header chat AI', max_length=100, verbose_name='Nama AI'),
        ),
    ]
