# Generated by Django 5.0.6 on 2026-01-20 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Metode')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Metode Pembayaran',
                'verbose_name_plural': 'Metode Pembayaran',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_transaksi', models.CharField(max_length=50, unique=True, verbose_name='Nomor Transaksi')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal')),
                ('nama_customer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nama Customer')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diskon')),
                ('pajak', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pajak')),
                ('total_harga', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Harga')),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jumlah Bayar')),
                ('kembalian', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kembalian')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('gudang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='produk.gudang', verbose_name='Gudang')),
                ('kasir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kasir')),
                ('metode_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.metodepembayaran', verbose_name='Metode Pembayaran')),
            ],
            options={
                'verbose_name': 'Transaksi POS',
                'verbose_name_plural': 'Transaksi POS',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='POSTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah')),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Harga Satuan')),
                ('diskon', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diskon')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk', verbose_name='Produk')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.postransaction', verbose_name='Transaksi')),
            ],
            options={
                'verbose_name': 'Item Transaksi POS',
                'verbose_name_plural': 'Item Transaksi POS',
            },
        ),
    ]
