# Generated by Django 5.0.6 on 2026-06-02 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('produk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='gudang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to='produk.gudang', verbose_name='Gudang'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='kasir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kasir'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produk.produk', verbose_name='Produk'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='satuan_transaksi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika menggunakan satuan asli produk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.satuan', verbose_name='Satuan Transaksi'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.postransaction', verbose_name='Transaksi'),
        ),
        migrations.AddIndex(
            model_name='metodepembayaran',
            index=models.Index(fields=['aktif', 'nama'], name='pos_pay_aktif_nama_idx'),
        ),
        migrations.AddIndex(
            model_name='metodepembayaran',
            index=models.Index(fields=['aktif', 'kode'], name='pos_pay_aktif_kode_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['tanggal', 'status'], name='pos_trx_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['gudang', 'tanggal'], name='pos_trx_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['kasir', 'tanggal'], name='pos_trx_kasir_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='pos_trx_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['customer', 'status'], name='pos_trx_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postransactionitem',
            index=models.Index(fields=['produk', 'transaction'], name='pos_item_prod_trx_idx'),
        ),
    ]
