# Generated by Django 5.0.6 on 2026-01-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='jatuh_tempo',
            field=models.DateField(blank=True, null=True, verbose_name='Jatuh Tempo'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Belum Lunas'), ('paid', 'Lunas'), ('cancelled', 'Dibatalkan')], default='paid', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='metode_pembayaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.metodepembayaran', verbose_name='Metode Pembayaran'),
        ),
    ]
