# Generated by Django 5.0.6 on 2026-02-02 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_postransaction_jatuh_tempo_postransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodepembayaran',
            name='deskripsi',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AddField(
            model_name='metodepembayaran',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dibuat Pada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodepembayaran',
            name='diubah_pada',
            field=models.DateTimeField(auto_now=True, verbose_name='Diubah Pada'),
        ),
        migrations.AddField(
            model_name='metodepembayaran',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='metode_pembayaran/', verbose_name='Gambar'),
        ),
    ]
