# Generated by Django 5.0.6 on 2026-02-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_add_gambar_deskripsi_to_metode'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodepembayaran',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo'),
        ),
    ]
