# Generated by Django 5.0.6 on 2026-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_add_saldo_to_metode'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodepembayaran',
            name='nama_pemilik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Pemilik'),
        ),
    ]
