# Generated by Django 5.0.6 on 2026-02-25 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penjualan', '0003_salesorder_metode_pembayaran'),
        ('pos', '0005_add_nama_pemilik'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_transactions', to='penjualan.customer', verbose_name='Customer'),
        ),
    ]
