# Generated by Django 6.0.3 on 2026-04-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_add_customer_fk'),
        ('produk', '0006_produk_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='jumlah_konversi',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Jumlah dalam satuan dasar produk, dihitung otomatis', max_digits=15, verbose_name='Jumlah (Satuan Dasar)'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='satuan_transaksi',
            field=models.ForeignKey(blank=True, help_text='Kosongkan jika menggunakan satuan asli produk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.satuan', verbose_name='Satuan Transaksi'),
        ),
    ]
