# Generated by Django 6.0.3 on 2026-05-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntansi', '0004_performance_indexes'),
        ('kas_bank', '0002_performance_indexes'),
        ('penjualan', '0005_performance_indexes'),
        ('pos', '0008_metodepembayaran_kas_bank_mapping'),
        ('produk', '0006_produk_metode_pembayaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metodepembayaran',
            index=models.Index(fields=['aktif', 'nama'], name='pos_pay_aktif_nama_idx'),
        ),
        migrations.AddIndex(
            model_name='metodepembayaran',
            index=models.Index(fields=['aktif', 'kode'], name='pos_pay_aktif_kode_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['tanggal', 'status'], name='pos_trx_tgl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['gudang', 'tanggal'], name='pos_trx_gdg_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['kasir', 'tanggal'], name='pos_trx_kasir_tgl_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['metode_pembayaran', 'status'], name='pos_trx_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['customer', 'status'], name='pos_trx_cust_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postransactionitem',
            index=models.Index(fields=['produk', 'transaction'], name='pos_item_prod_trx_idx'),
        ),
    ]
