# Generated by Django 6.0.3 on 2026-05-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_postransactionitem_hpp_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodepembayaran',
            name='tipe',
            field=models.CharField(choices=[('tunai', 'Tunai'), ('non_tunai', 'Non-Tunai')], default='tunai', help_text='Tunai = pembayaran langsung/cash, Non-Tunai = transfer bank, QRIS, dll', max_length=20, verbose_name='Tipe Pembayaran'),
        ),
    ]
