# Generated by Django 6.0.3 on 2026-05-22 09:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_add_tipe_metode_pembayaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodepembayaran',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='metode_pembayaran/', validators=[apps.core.validators.validate_image_file], verbose_name='Gambar'),
        ),
    ]
